#!/usr/bin/env julia

using Pkg
Pkg.activate(@__DIR__)

using Printf

root = dirname(@__DIR__)
using GIModel
using GIPaper

# Heavy-heavy diagnostics: reference rows → compare_reference per spectrum file.

params_path = default_parameters_path()
params, mq = load_parameters_and_quark_masses(params_path)
report_path = joinpath(root, "docs", "residual_reports", "heavy_quarkonium_diagnostics.md")
mkpath(dirname(report_path))

const SECTORS = [
    ("charmonium", reference_spectrum_path("charmonium"), state -> true),
    ("bottomonium", reference_spectrum_path("bottomonium"), state -> true),
    ("bcbar", reference_spectrum_path("b_flavored"), state -> state.sector == "bottom_charm"),
]

function row_label(row)
    @sprintf("%d^%d%s_%d", row.n, row.multiplicity, row.L, row.J)
end

function center_groups(rows)
    groups = Dict{Tuple{Int,String},Vector{eltype(rows)}}()
    for row in rows
        push!(get!(groups, (row.n, row.L), eltype(rows)[]), row)
    end
    out = Dict{Tuple{Int,String},NamedTuple}()
    for (key, group) in groups
        weights = [2 * row.J + 1 for row in group]
        wsum = sum(weights)
        ref = sum(w * row.reference_GeV for (w, row) in zip(weights, group)) / wsum
        pred = sum(w * row.predicted_GeV for (w, row) in zip(weights, group)) / wsum
        out[key] = (
            n = key[1],
            L = key[2],
            states = length(group),
            ref = ref,
            pred = pred,
            residual = 1000 * (pred - ref),
        )
    end
    out
end

function split_row(rows, label_a, label_b)
    bylabel = Dict(row_label(row) => row for row in rows)
    haskey(bylabel, label_a) && haskey(bylabel, label_b) || return nothing
    a = bylabel[label_a]
    b = bylabel[label_b]
    ref = 1000 * (a.reference_GeV - b.reference_GeV)
    pred = 1000 * (a.predicted_GeV - b.predicted_GeV)
    (name = "$label_a - $label_b", ref = ref, pred = pred, error = pred - ref)
end

function spacing_row(centers, key_a, key_b)
    haskey(centers, key_a) && haskey(centers, key_b) || return nothing
    a = centers[key_a]
    b = centers[key_b]
    ref = 1000 * (a.ref - b.ref)
    pred = 1000 * (a.pred - b.pred)
    (
        name = "$(key_a[1])$(key_a[2]) - $(key_b[1])$(key_b[2])",
        ref = ref,
        pred = pred,
        error = pred - ref,
    )
end

"""Share of `sum(r_i^2)` that is removed by subtracting the mean residual (common offset proxy)."""
function fraction_offset_explains(residuals_MeV::Vector{Float64})
    isempty(residuals_MeV) && return 0.0
    sst = sum(abs2, residuals_MeV)
    sst <= 0.0 && return 0.0
    o = sum(residuals_MeV) / length(residuals_MeV)
    sc = sum((r - o)^2 for r in residuals_MeV)
    return 1.0 - sc / sst
end

function spacing_error_from_rows(sp_rows)
    errs = Float64[]
    for row in sp_rows
        isnothing(row) && continue
        push!(errs, row.error)
    end
    isempty(errs) && return (0.0, 0.0, 0)
    n = length(errs)
    rms = sqrt(sum(abs2, errs) / n)
    mae = sum(abs, errs) / n
    return (rms, mae, n)
end

function emit_split_table(io, title, rows)
    valid = [row for row in rows if !isnothing(row)]
    isempty(valid) && return
    println(io, "### ", title)
    println(io)
    println(io, "| quantity | reference MeV | model MeV | error MeV |")
    println(io, "|---|---:|---:|---:|")
    for row in valid
        println(
            io,
            @sprintf(
                "| `%s` | %.1f | %.1f | %+7.1f |",
                row.name,
                row.ref,
                row.pred,
                row.error
            )
        )
    end
    println(io)
end

function same_j_pwave_mixing_diagnostic(params, masses; ngrid = 450, rmax = 24.0)
    solution = channel_solution(
        params, masses, 1;
        nlevels = 1,
        solver = FiniteDifferenceSolver(ngrid = ngrid, rmax = rmax, kinetic = :relativistic),
    )
    radial = radial_wave(solution, 1)
    offdiag = spin_orbit_mixing_components(
        params,
        masses,
        "P",
        radial;
    )
    triplet_shift = fine_structure_split(
        params,
        masses,
        FineStructureMultiplet("P", 3, 1),
        radial;
    )
    central = solution.eigenvalues_GeV[1]
    mix = same_j_mixing(central, central + triplet_shift, offdiag.total)
    return (
        singlet = central,
        triplet = central + triplet_shift,
        offdiag = offdiag.total,
        low = mix.masses[1],
        high = mix.masses[2],
        theta = mix.theta_deg,
        theta_complement = mix.theta_deg > 0 ? mix.theta_deg - 90 : mix.theta_deg + 90,
    )
end

open(report_path, "w") do io
    println(io, "# Heavy Quarkonium Diagnostics")
    println(io)
    println(io, "Generated by `julia GIPaper/scripts/analyze_heavy_quarkonium.jl`.")
    println(io, numerics_provenance(FiniteDifferenceSolver()))
    println(io)
    println(
        io,
        "Purpose: check whether the active GI central path reproduces `ccbar`/`bbbar` and the Fig. 9 `bcbar` panel, then separate any remaining mismatch into spin-averaged centers, radial/orbital spacings, and spin splittings.",
    )
    println(io)
    active = central_potential_path(params)
    println(io, "Active central path: `", active.name, "` — ", active.paper_refs)
    println(io)

    for (sector, path, keep_state) in SECTORS
        reference = filter(keep_state, GIPaper.load_reference_spectrum(path))
        rows = compare_reference(
            params,
            mq,
            reference;
            contact_hyperfine = true,
            use_fine_structure = params.fine_structure.enabled,
            kinetic = :relativistic,
        )
        residuals = [row.residual_MeV for row in rows]
        offset = sum(residuals) / length(residuals)
        centered_abs = [abs(row.residual_MeV - offset) for row in rows]
        centers = center_groups(rows)

        println(io, "## ", sector)
        println(io)
        println(io, @sprintf("- rows: `%d`", length(rows)))
        println(io, @sprintf("- mean residual/common offset: `%+.1f MeV`", offset))
        println(
            io,
            @sprintf(
                "- mean absolute residual: `%.1f MeV`",
                sum(abs.(residuals)) / length(residuals)
            )
        )
        println(
            io,
            @sprintf(
                "- mean absolute residual after removing common offset: `%.1f MeV`",
                sum(centered_abs) / length(centered_abs)
            )
        )
        f_off = fraction_offset_explains(residuals)
        println(
            io,
            @sprintf(
                "- approximate share of *squared* residuals explained by a single common offset: `%.0f%%` (order-of-magnitude; not a full variance decomposition across physics channels)",
                100 * f_off,
            ),
        )
        println(io)

        println(io, "### Multiplet Centers")
        println(io)
        println(
            io,
            "| multiplet | states | reference GeV | model GeV | residual MeV | offset-corrected MeV |",
        )
        println(io, "|---|---:|---:|---:|---:|---:|")
        for key in sort(collect(keys(centers)); by = x -> (x[2], x[1]))
            c = centers[key]
            println(
                io,
                @sprintf(
                    "| `%d%s` | %d | %.3f | %.3f | %+7.1f | %+7.1f |",
                    c.n,
                    c.L,
                    c.states,
                    c.ref,
                    c.pred,
                    c.residual,
                    c.residual - offset,
                ),
            )
        end
        println(io)

        sp_rows = [
            spacing_row(centers, (2, "S"), (1, "S")),
            spacing_row(centers, (3, "S"), (1, "S")),
            spacing_row(centers, (1, "P"), (1, "S")),
            spacing_row(centers, (1, "D"), (1, "P")),
            spacing_row(centers, (2, "P"), (1, "P")),
            spacing_row(centers, (2, "D"), (1, "D")),
        ]
        rms_s, mae_s, n_s = spacing_error_from_rows(sp_rows)
        println(
            io,
            "- radial/orbital spacing errors (this table): RMSE = `",
            @sprintf("%.1f", rms_s),
            " MeV`, mean abs = `",
            @sprintf("%.1f", mae_s),
            " MeV` over `",
            n_s,
            "` available rows",
        )
        println(io)
        emit_split_table(io, "Radial And Orbital Spacings", sp_rows)

        emit_split_table(
            io,
            "Spin Splittings",
            [
                split_row(rows, "1^3S_1", "1^1S_0"),
                split_row(rows, "2^3S_1", "2^1S_0"),
                split_row(rows, "1^3P_2", "1^3P_1"),
                split_row(rows, "1^3P_1", "1^3P_0"),
                split_row(rows, "2^3P_2", "2^3P_1"),
                split_row(rows, "2^3P_1", "2^3P_0"),
                split_row(rows, "1^3D_3", "1^3D_2"),
                split_row(rows, "1^3D_2", "1^3D_1"),
            ],
        )

        masses = reference_meson(mq, reference[1]).constituent_masses
        mix = same_j_pwave_mixing_diagnostic(params, masses)
        println(io, "### Same-J 1P Mixing Diagnostic")
        println(io)
        println(
            io,
            "Diagnostic FD-basis `(^1P_1, ^3P_1)` matrix, using the antisymmetric spin-orbit term. Angle convention: `low = cos(theta) ^1P_1 + sin(theta) ^3P_1`; the complementary angle is shown because the paper's label/sign convention may choose the orthogonal state.",
        )
        println(io)
        println(
            io,
            "| m1 GeV | m2 GeV | ^1P1 diag GeV | ^3P1 diag GeV | offdiag MeV | low GeV | high GeV | theta deg | complement deg |",
        )
        println(io, "|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        println(
            io,
            @sprintf(
                "| %.3f | %.3f | %.3f | %.3f | %+7.2f | %.3f | %.3f | %+6.1f | %+6.1f |",
                masses.m1_GeV,
                masses.m2_GeV,
                mix.singlet,
                mix.triplet,
                1000 * mix.offdiag,
                mix.low,
                mix.high,
                mix.theta,
                mix.theta_complement,
            ),
        )
        println(io)
    end

    println(io)
    println(io, "## Where to go next (strategy)")
    println(io)
    println(
        io,
        "1. Heavy-quarkonium centers and radial/orbital spacings are reproduced at the few-MeV level with the active `appendix_a_momentum_sandwich` central path.",
    )
    println(
        io,
        "2. The active contact, tensor, and spin–orbit terms now include GI-style momentum-factor sandwiches; tensor and spin–orbit radial kernels are derived from the smeared Appendix-A `G̃(r)`/`S̃(r)` derivatives.",
    )
    println(
        io,
        "3. The next equal-mass refinement is to audit remaining extraction/rounding ambiguity in the plotted charmonium labels and compare the perturbative FD treatment against the paper's HO-basis implementation order.",
    )
    println(
        io,
        "4. Heavy–light and light sectors now include available unequal-mass antisymmetric spin–orbit assignment, but still require same-J tensor mixing, annihilation/mixing, and eventually coupled-channel physics; do not read their residuals as a failure of the heavy-heavy GI reproduction.",
    )
    println(
        io,
        "5. Close the extraction loop: log text-vs-figure issues in `data/raw/extraction_audit.csv` and promote reference rows to `data/clean/` with provenance before arguing about sub-5-MeV agreement.",
    )
    println(io)
end

println("wrote $report_path")
