#!/usr/bin/env julia

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."); io = devnull)

using GIModel
using Printf

const ROOT = dirname(@__DIR__)
const PARAMS_PATH = joinpath(dirname(ROOT), "data", "parameters.provisional.toml")
const REPORT = joinpath(ROOT, "docs", "residual_reports", "ho_convergence.md")

function main()
    params, mq = load_parameters_and_quark_masses(PARAMS_PATH)
    solver = OscillatorSolver()
    cases = (
        ("1S0", FineStructureMultiplet("S", 1, 0)),
        ("3P2", FineStructureMultiplet("P", 3, 2)),
    )
    rows = NamedTuple[]
    for flavor in ("q", "s", "c", "b"), (label, multiplet) in cases
        masses = ConstituentMasses(mq[flavor], mq[flavor])
        solution = fixed_channel_solution(
            params, masses, multiplet; solver = solver, nlevels = 6,
        )
        certificate = solution.convergence
        certificate.status == :converged || error(
            "$flavor $label returned an uncertified HO solution",
        )
        push!(rows, (
            flavor = flavor,
            sector = label,
            nbasis = certificate.nbasis,
            beta = certificate.beta_GeV,
            delta_MeV = 1000 * certificate.energy_delta_GeV,
            overlap_defect = certificate.max_wave_overlap_defect,
        ))
    end

    open(REPORT, "w") do io
        println(io, "# Native HO Convergence Audit")
        println(io)
        println(io, "Generated by `julia GIPaper/scripts/audit_ho_convergence.jl`.")
        println(io, numerics_provenance(solver))
        println(io)
        println(io, "The audit requests six radial levels in the two numerically hardest")
        println(io, "representative fixed sectors: the contact-distorted `1S0` channel and")
        println(io, "the spin-orbit/tensor `3P2` channel. Equal-flavor q, s, c, and b masses")
        println(io, "span the diffuse-to-compact range of the paper. Open-flavor masses lie")
        println(io, "between these endpoint scales; higher-L sectors are less singular.")
        println(io)
        println(io, "A solution is returned only after every requested eigenvalue changes by")
        println(io, "at most 0.1 MeV on two consecutive basis refinements. The wave-overlap")
        println(io, "defect is recorded independently for PA-17/PA-18 observable audits.")
        println(io)
        println(io, "| flavor | sector | achieved nbasis | refined beta GeV | final max delta MeV | max overlap defect |")
        println(io, "|---|---|---:|---:|---:|---:|")
        for row in rows
            @printf(
                io,
                "| `%s` | `^%s` | %d | %.5f | %.6f | %.3e |\n",
                row.flavor,
                row.sector,
                row.nbasis,
                row.beta,
                row.delta_MeV,
                row.overlap_defect,
            )
        end
        println(io)
        println(io, "All calibration sectors converged below the default hard cap. A beta")
        println(io, "minimum at either declared endpoint or exhaustion of `max_nbasis` is a")
        println(io, "hard error; neither condition can enter a production spectrum silently.")
    end
    println("wrote ", REPORT)
end

main()
