#!/usr/bin/env julia
# Build diagnostics that separate non-mixing score quality from S-wave contact
# hyperfine stress.

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Dates
using Printf

root = dirname(@__DIR__)
using GIModel
using GIPaper

params_path = joinpath(dirname(root), "data", "parameters.provisional.toml")
params, mq = load_parameters_and_quark_masses(params_path)
params_ho = GIModel.with_basis(params, HarmonicOscillatorBasis)

function with_contact_momentum_sandwich(params::GIParameters{Basis}, enabled::Bool) where {Basis}
    f = params.factors
    return GIParameters{Basis}(
        potential = params.potential,
        central = params.central,
        smearing = params.smearing,
        factors = RelativisticFactors(
            epsilon_c = f.epsilon_c,
            epsilon_t = f.epsilon_t,
            epsilon_so_vector = f.epsilon_so_vector,
            epsilon_so_scalar = f.epsilon_so_scalar,
            contact_momentum_sandwich = enabled,
            fine_structure_momentum_sandwich = f.fine_structure_momentum_sandwich,
            fine_structure_smeared_kernels = f.fine_structure_smeared_kernels,
        ),
        fine_structure = params.fine_structure,
        annihilation = params.annihilation,
    )
end

data_dir = joinpath(root, "data")
report_dir = joinpath(root, "docs", "residual_reports")
mkpath(report_dir)

params_diagonal_contact = with_contact_momentum_sandwich(params, false)
all_rows = NamedTuple[]
all_rows_ho = NamedTuple[]
contact_rows = NamedTuple[]

for fn in sort(readdir(data_dir))
    startswith(fn, "reference_spectrum_") && endswith(fn, ".csv") || continue
    base = fn[(length("reference_spectrum_")+1):(end-length(".csv"))]
    reference = GIPaper.load_reference_spectrum(joinpath(data_dir, fn))
    rows = compare_reference(
        params,
        mq,
        reference;
        contact_hyperfine = true,
        use_fine_structure = params.fine_structure.enabled,
        kinetic = :relativistic,
        isoscalar_pseudoscalar_annihilation =
            base == "isoscalar" ? :table_iii : :none,
        strange_mass_GeV = mq["s"],
    )
    append!(all_rows, rows)

    rows_ho = compare_reference(
        params_ho,
        mq,
        reference;
        contact_hyperfine = true,
        use_fine_structure = params_ho.fine_structure,
        kinetic = :relativistic,
    )
    append!(all_rows_ho, rows_ho)

    # Same central solves, contact evaluated without the momentum sandwich.
    diagonal_rows = compare_reference(
        params_diagonal_contact,
        mq,
        reference;
        contact_hyperfine = true,
        use_fine_structure = params.fine_structure.enabled,
        kinetic = :relativistic,
    )

    for (active, diagonal) in zip(rows, diagonal_rows)
        active.L == "S" || continue
        active.multiplicity in (1, 3) || continue
        push!(
            contact_rows,
            (
                sector = active.sector,
                state = @sprintf("%d^%d%s_%d", active.n, active.multiplicity, active.L, active.J),
                reference_GeV = active.reference_GeV,
                active_contact_MeV = 1000 * active.contact_shift_GeV,
                diagonal_contact_MeV = 1000 * diagonal.contact_shift_GeV,
                residual_MeV = active.residual_MeV,
                mixing_prone = mixing_prone_state(active),
            ),
        )
    end
end

summary = nonmixing_deviation_summary(all_rows)
summary_ho = nonmixing_deviation_summary(all_rows_ho)

function mean_abs_residual(rows)
    vals = [abs(row.residual_MeV) for row in rows]
    return isempty(vals) ? NaN : sum(vals) / length(vals)
end

function max_abs_residual(rows)
    vals = [abs(row.residual_MeV) for row in rows]
    return isempty(vals) ? NaN : maximum(vals)
end

function fmt_mev(x)
    return isnan(x) ? "n/a" : @sprintf("%.1f", x)
end

open(joinpath(report_dir, "nonmixing_scorecard.md"), "w") do io
    println(io, "# Non-Mixing Residual Scorecard")
    println(io)
    println(io, "Generated by `julia GIPaper/scripts/audit_nonmixing_contact.jl`.")
    println(io, "Host generation time: ", Dates.format(Dates.now(), dateformat"yyyy-mm-dd\THH:MM"))
    println(io)
    println(
        io,
        "Rows marked as likely to require still-missing explicit mixing are excluded: unassigned same-`J` tensor/radial candidates, calibrated (fitted) pseudoscalar rows, and isoscalar rows without an assigned flavor partner. Open-flavor `^1L_J`/`^3L_J` rows, assigned triplet `L/L'` tensor pairs, and isoscalar rows assigned by the `:table_iii` scheme (ideal mixing or general Eq. (16)) are included.",
    )
    println(io)
    println(io, "| sector | included | excluded | mean abs deviation MeV | max abs deviation MeV |")
    println(io, "|---|---:|---:|---:|---:|")
    for row in sort(summary; by = r -> (isnan(r.mean_abs_deviation_MeV), r.mean_abs_deviation_MeV))
        mean_s = fmt_mev(row.mean_abs_deviation_MeV)
        max_s = fmt_mev(row.max_abs_deviation_MeV)
        println(
            io,
            @sprintf(
                "| `%s` | %d | %d | %s | %s |",
                row.sector,
                row.n_included,
                row.n_excluded_mixing_prone,
                mean_s,
                max_s,
            ),
        )
    end
end

function row_key(row)
    return (row.sector, row.state, row.L, row.n, row.J, row.multiplicity, row.reference_GeV)
end

fd_by_key = Dict(row_key(row) => row for row in all_rows if !mixing_prone_state(row))
ho_by_key = Dict(row_key(row) => row for row in all_rows_ho if !mixing_prone_state(row))
common_keys = sort(collect(intersect(keys(fd_by_key), keys(ho_by_key))); by = x -> (x[1], x[4], x[3], x[6], x[5], x[2]))
summary_ho_by_sector = Dict(row.sector => row for row in summary_ho)

open(joinpath(report_dir, "basis_nonmixing_comparison.md"), "w") do io
    println(io, "# Non-Mixing Basis Comparison")
    println(io)
    println(io, "Generated by `julia GIPaper/scripts/audit_nonmixing_contact.jl`.")
    println(io, "FD = current `FiniteDifferenceBasis`; HO = first finite `HarmonicOscillatorBasis` audit path.")
    println(io)
    println(
        io,
        "HO caveat: the spin-independent Hamiltonian is assembled in the oscillator subspace with a per-channel variational beta scan. One beta is used for each orthogonal channel set, chosen by minimizing the last requested level; spin-dependent expectations are evaluated on reconstructed mesh wavefunctions.",
    )
    println(io)
    println(io, "## Sector Summary")
    println(io)
    println(io, "| sector | rows | excluded | FD mean abs | FD max abs | HO mean abs | HO max abs |")
    println(io, "|---|---:|---:|---:|---:|---:|---:|")
    for fd in sort(summary; by = r -> (isnan(r.mean_abs_deviation_MeV), r.mean_abs_deviation_MeV))
        ho = get(summary_ho_by_sector, fd.sector, nothing)
        ho_mean = isnothing(ho) ? "n/a" : fmt_mev(ho.mean_abs_deviation_MeV)
        ho_max = isnothing(ho) ? "n/a" : fmt_mev(ho.max_abs_deviation_MeV)
        fd_mean = fmt_mev(fd.mean_abs_deviation_MeV)
        fd_max = fmt_mev(fd.max_abs_deviation_MeV)
        println(
            io,
            @sprintf(
                "| `%s` | %d | %d | %s | %s | %s | %s |",
                fd.sector,
                fd.n_included,
                fd.n_excluded_mixing_prone,
                fd_mean,
                fd_max,
                ho_mean,
                ho_max,
            ),
        )
    end
    println(io)
    println(io, "## State Table")
    println(io)
    println(io, "| sector | state | ref | FD pred | HO pred | FD resid | HO resid | HO-FD |")
    println(io, "|---|---|---:|---:|---:|---:|---:|---:|")
    for key in common_keys
        fd = fd_by_key[key]
        ho = ho_by_key[key]
        label = @sprintf("%d^%d%s_%d", fd.n, fd.multiplicity, fd.L, fd.J)
        println(
            io,
            @sprintf(
                "| `%s` | `%s` | %.3f | %.3f | %.3f | %+7.1f | %+7.1f | %+7.1f |",
                fd.sector,
                label,
                fd.reference_GeV,
                fd.predicted_GeV,
                ho.predicted_GeV,
                fd.residual_MeV,
                ho.residual_MeV,
                1000 * (ho.predicted_GeV - fd.predicted_GeV),
            ),
        )
    end
end

function compare_isoscalar_branch(params, reference, mass)
    meson = Meson(LightQuark(mass), LightQuark(mass))
    levels = [BasisState(r.n, r.L, r.multiplicity, r.J) for r in reference]
    spec = compute_spectrum(
        params,
        meson;
        levels = levels,
        kinetic = :relativistic,
        contact_hyperfine = true,
        use_fine_structure = params.fine_structure.enabled,
    )
    return [
        (
            state = r.composition,
            n = r.n,
            multiplicity = r.multiplicity,
            L = r.L,
            J = r.J,
            predicted_GeV = st.mass_GeV,
        ) for (r, st) in zip(reference, spec.states)
    ]
end

function isoscalar_branch_key(row)
    return (row.state, row.n, row.multiplicity, row.L, row.J)
end

isoscalar_reference =
    GIPaper.load_reference_spectrum(joinpath(data_dir, "reference_spectrum_isoscalar.csv"))
isoscalar_nn_rows = compare_isoscalar_branch(params, isoscalar_reference, mq["q"])
isoscalar_ss_rows = compare_isoscalar_branch(params, isoscalar_reference, mq["s"])
nn_by_key = Dict(isoscalar_branch_key(row) => row for row in isoscalar_nn_rows)
ss_by_key = Dict(isoscalar_branch_key(row) => row for row in isoscalar_ss_rows)
isoscalar_groups = Dict{Tuple{String,Int,Int,String,Int},Vector{GIPaper.ReferenceState}}()
for row in isoscalar_reference
    key = (row.composition, row.n, row.multiplicity, row.L, row.J)
    push!(get!(isoscalar_groups, key, GIPaper.ReferenceState[]), row)
end
isoscalar_branch_rows = NamedTuple[]
for (key, refs) in isoscalar_groups
    length(refs) >= 2 || continue
    ordered = sort(refs; by = row -> row.mass_GeV)
    model_key = key
    nn = get(nn_by_key, model_key, nothing)
    ss = get(ss_by_key, model_key, nothing)
    isnothing(nn) || push!(
        isoscalar_branch_rows,
        (
            state = key[1],
            branch = "lower vs nn",
            reference_GeV = first(ordered).mass_GeV,
            predicted_GeV = nn.predicted_GeV,
            residual_MeV = 1000 * (nn.predicted_GeV - first(ordered).mass_GeV),
        ),
    )
    isnothing(ss) || push!(
        isoscalar_branch_rows,
        (
            state = key[1],
            branch = "upper vs ss",
            reference_GeV = last(ordered).mass_GeV,
            predicted_GeV = ss.predicted_GeV,
            residual_MeV = 1000 * (ss.predicted_GeV - last(ordered).mass_GeV),
        ),
    )
end

open(joinpath(report_dir, "light_sector_audit.md"), "w") do io
    println(io, "# Light-Sector Mismatch Audit")
    println(io)
    println(io, "Generated by `julia GIPaper/scripts/audit_nonmixing_contact.jl`.")
    println(io)
    println(
        io,
        "This report separates raw sector residuals from the rows that should be judged before explicit mixing/annihilation machinery exists.",
    )
    println(io)
    println(io, "## Raw vs Guardrailed Sectors")
    println(io)
    println(io, "| sector | raw rows | raw mean abs | raw max abs | non-mixed rows | non-mixed mean abs | non-mixed max abs | excluded |")
    println(io, "|---|---:|---:|---:|---:|---:|---:|---:|")
    summary_by_sector = Dict(row.sector => row for row in summary)
    for sector in sort(unique(row.sector for row in all_rows))
        raw = [row for row in all_rows if row.sector == sector]
        kept = [row for row in raw if !mixing_prone_state(row)]
        summ = summary_by_sector[sector]
        println(
            io,
            @sprintf(
                "| `%s` | %d | %s | %s | %d | %s | %s | %d |",
                sector,
                length(raw),
                fmt_mev(mean_abs_residual(raw)),
                fmt_mev(max_abs_residual(raw)),
                length(kept),
                fmt_mev(summ.mean_abs_deviation_MeV),
                fmt_mev(summ.max_abs_deviation_MeV),
                summ.n_excluded_mixing_prone,
            ),
        )
    end
    println(io)
    println(io, "## Isoscalar Two-Branch Sanity Check")
    println(io)
    println(
        io,
        "The digitized isoscalar figure lists mixed `n nbar / s sbar` pairs. Comparing both partners to the same `n nbar` radial solution creates an artificial sector-wide failure. As a diagnostic only, the lower member of each pair is compared to an unmixed `n nbar` prediction and the upper member to an unmixed `s sbar` prediction.",
    )
    branch_abs = [abs(row.residual_MeV) for row in isoscalar_branch_rows]
    println(
        io,
        @sprintf(
            "Two-branch diagnostic: rows=%d, mean abs=%.1f MeV, max abs=%.1f MeV.",
            length(isoscalar_branch_rows),
            sum(branch_abs) / length(branch_abs),
            maximum(branch_abs),
        ),
    )
    println(io)
    println(io, "| state | branch | ref | pred | residual MeV |")
    println(io, "|---|---|---:|---:|---:|")
    for row in sort(isoscalar_branch_rows; by = row -> -abs(row.residual_MeV))[1:min(16, length(isoscalar_branch_rows))]
        println(
            io,
            @sprintf(
                "| `%s` | `%s` | %.3f | %.3f | %+7.1f |",
                row.state,
                row.branch,
                row.reference_GeV,
                row.predicted_GeV,
                row.residual_MeV,
            ),
        )
    end
    println(io)
    println(io, "## Audit Read")
    println(io)
    println(
        io,
        "The contrast across sectors is now diagnostic: heavy, heavy-light, strange, and non-mixed isovector rows are already at the few-to-tens of MeV scale, while raw isoscalar residuals mostly reflect missing flavor mixing/annihilation assignment.",
    )
    println(
        io,
        "The calibrated P1-style pseudoscalar annihilation path now removes the raw `^1S_0` isoscalar failures from the main scorecard. The two-branch sanity table is retained as a pre-annihilation diagnostic showing why that block was required.",
    )
    println(
        io,
        "The remaining raw isoscalar residuals are no longer concentrated in pseudoscalars; they mostly reflect the still-missing general `n nbar`/`s sbar` flavor-mixing assignment for paired isoscalar states.",
    )
end

open(joinpath(report_dir, "contact_hyperfine_audit.md"), "w") do io
    println(io, "# Contact Hyperfine Audit")
    println(io)
    println(io, "Generated by `julia GIPaper/scripts/audit_nonmixing_contact.jl`.")
    println(io)
    println(io, "## Paper Clues")
    println(io)
    println(
        io,
        "- Appendix A says the contact, tensor, vector spin-orbit, and scalar spin-orbit potentials are modified by momentum-dependent `m/E` factors, replacing naive light-quark mass denominators by energy denominators when `epsilon_i = 0`.",
    )
    println(
        io,
        "- This requires a side exponent `1/2 + epsilon_i` in the Hermitian sandwich. A smaller side exponent only partially replaces `1/(m1 m2)` by `1/(E1 E2)` and leaves light-quark contact terms too large.",
    )
    println(
        io,
        "- The smearing width in (A9) is flavor dependent and was designed so light-quark systems do not inherit an unchecked `1/(m1 m2)` contact singularity.",
    )
    println(
        io,
        "- GI evaluated the nonlocal `f(p) V(r) f(p)` operators in a large harmonic-oscillator basis; this repo currently evaluates the same idea on the finite-difference `p^2` eigenbasis, now selected through `GIParameters{Basis}` dispatch.",
    )
    println(
        io,
        "- The first GI diagonalization is already in fixed `L,S,J` sectors, so the contact term is part of the S-wave radial problem rather than only a first-order correction on a spin-independent wavefunction. This matters most in the pion/kaon-sized light pseudoscalar splittings.",
    )
    println(io)
    println(io, "## Sector-Level Contact Stress")
    println(io)
    println(io, "| sector | S rows | mean abs active contact MeV | max abs active contact MeV | mean active/diagonal magnitude | mean abs residual MeV |")
    println(io, "|---|---:|---:|---:|---:|---:|")
    for sector in sort(unique(row.sector for row in contact_rows))
        rows = [row for row in contact_rows if row.sector == sector && !row.mixing_prone]
        isempty(rows) && continue
        active_abs = abs.([row.active_contact_MeV for row in rows])
        residual_abs = abs.([row.residual_MeV for row in rows])
        ratios = [
            abs(row.diagonal_contact_MeV) > 0 ? abs(row.active_contact_MeV / row.diagonal_contact_MeV) : NaN
            for row in rows
        ]
        ratios = [x for x in ratios if isfinite(x)]
        println(
            io,
            @sprintf(
                "| `%s` | %d | %.1f | %.1f | %.3f | %.1f |",
                sector,
                length(rows),
                sum(active_abs) / length(active_abs),
                maximum(active_abs),
                sum(ratios) / length(ratios),
                sum(residual_abs) / length(residual_abs),
            ),
        )
    end
    println(io)
    println(io, "## Largest Non-Mixed S-Wave Residuals")
    println(io)
    println(io, "| sector | state | residual MeV | active contact MeV | diagonal contact MeV |")
    println(io, "|---|---|---:|---:|---:|")
    kept = [row for row in contact_rows if !row.mixing_prone]
    for row in sort(kept; by = r -> -abs(r.residual_MeV))[1:min(16, length(kept))]
        println(
            io,
            @sprintf(
                "| `%s` | `%s` | %+7.1f | %+7.1f | %+7.1f |",
                row.sector,
                row.state,
                row.residual_MeV,
                row.active_contact_MeV,
                row.diagonal_contact_MeV,
            ),
        )
    end
    println(io)
    println(io, "## Audit Read")
    println(io)
    println(
        io,
        "The non-mixing scorecard is the central guardrail: if spin-averaged, non-mixed centers are good while S-wave rows remain split in opposite directions, the mismatch is localized to contact hyperfine strength/order rather than to the central potential.",
    )
    println(
        io,
        "After enforcing the Appendix-A side exponent and diagonalizing the finite-difference S-wave contact operator nonperturbatively, the light pseudoscalar ground-state mismatch changes from the dominant failure to a bounded residual (`isovector 1^1S_0` and `strange 1^1S_0` are now tens, not hundreds, of MeV). The remaining edge is consistent with the paper's warning that pseudoscalar channels are unusually sensitive to relativistic smearing and annihilation/chiral dynamics.",
    )
end

println("wrote ", joinpath(report_dir, "nonmixing_scorecard.md"))
println("wrote ", joinpath(report_dir, "light_sector_audit.md"))
println("wrote ", joinpath(report_dir, "contact_hyperfine_audit.md"))
println("wrote ", joinpath(report_dir, "basis_nonmixing_comparison.md"))
