#!/usr/bin/env julia
# Audit of the 13 same-J mixing angles quoted in the text of Godfrey & Isgur,
# Phys. Rev. D 32, 189 (1985): strange (Fig. 4 caption), charmed (Fig. 7
# caption), and b-flavored (Fig. 9 caption) sectors.
#
# Paper convention (identical matrix printed in all three captions):
#
#   [ Q_low  ]   [  cos(theta_nL)  sin(theta_nL) ] [ n ^1L_L ]
#   [ Q_high ] = [ -sin(theta_nL)  cos(theta_nL) ] [ n ^3L_L ]
#
# so Q_low = cos(theta) |n ^1L_L> + sin(theta) |n ^3L_L>.  Our
# `same_j_mixing` (src/spin_fine_structure.jl) uses the *same* definition:
# lower-eigenvalue eigenvector of the (singlet, triplet)-ordered 2x2 block,
# singlet component normalized >= 0, theta = atan2(v_triplet, v_singlet).
# Hence theta_paper = theta_model identically (see the report's convention
# section for the two sign conventions that enter the off-diagonal element).
#
# Angles are read from the public spectrum API only: compute_spectrum ->
# spectrum_state(...).mixings (mechanism "antisymmetric_spin_orbit").

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Dates
using Printf

root = dirname(@__DIR__)
using GIModel
using GIPaper: quark_for   # paper flavor label -> quark object

params_path = joinpath(dirname(root), "data", "parameters.provisional.toml")
params, mq = load_parameters_and_quark_masses(params_path)

const L_OF = Dict("P" => 1, "D" => 2, "F" => 3, "G" => 4)

# The 13 text-quoted angles: (n, L, paper theta in degrees), grouped by
# sector with the paper's flavor ordering (flavor1 = quark, flavor2 = antiquark).
sectors = [
    (label = "u sbar", f1 = :u, f2 = :s,
     rows = [(1, "P", 34.0), (1, "D", 33.0), (2, "P", 15.0),
             (1, "F", 32.0), (2, "D", 25.0), (1, "G", 33.0)],
     src = "Fig. 4 caption (PDF p. 7; vision OCR ~line 348)"),
    (label = "c ubar", f1 = :c, f2 = :u,
     rows = [(1, "P", -41.0), (1, "D", -39.0)],
     src = "Fig. 7 caption (PDF p. 9; vision OCR ~line 402)"),
    (label = "c sbar", f1 = :c, f2 = :s,
     rows = [(1, "P", -44.0), (1, "D", -39.0)],
     src = "Fig. 7 caption (PDF p. 9; vision OCR ~line 402)"),
    (label = "b ubar", f1 = :b, f2 = :u,
     rows = [(1, "P", -43.0)],
     src = "Fig. 9 caption (PDF p. 10; vision OCR ~line 432)"),
    (label = "b sbar", f1 = :b, f2 = :s,
     rows = [(1, "P", -45.0)],
     src = "Fig. 9 caption (PDF p. 10; vision OCR ~line 432)"),
    (label = "b cbar", f1 = :b, f2 = :c,
     rows = [(1, "P", -53.0)],
     src = "Fig. 9 caption (PDF p. 10; vision OCR ~line 432)"),
]

# Angle quoted if the low/high labels were exchanged (theta defined mod 180;
# a label swap shifts by 90 within (-90, 90]).
complement_deg(theta) = theta > 0 ? theta - 90.0 : theta + 90.0

same_j_mix(state) =
    only(filter(m -> m.mechanism == "antisymmetric_spin_orbit", state.mixings))

results = NamedTuple[]
for sec in sectors
    levels = BasisState[]
    for (n, L, _) in sec.rows
        push!(levels, BasisState(n, L, 1, L_OF[L]))
        push!(levels, BasisState(n, L, 3, L_OF[L]))
    end
    meson = Meson(quark_for(mq, sec.f1), quark_for(mq, sec.f2))
    println("computing spectrum for ", flavor_label(meson), " ...")
    # Production solver settings (defaults): ngrid = 450, rmax = 24.0.
    spec = compute_spectrum(params, meson; levels = levels)
    for (n, L, paper) in sec.rows
        s1 = spectrum_state(spec, n, L, 1, L_OF[L])   # n ^1L_L
        s3 = spectrum_state(spec, n, L, 3, L_OF[L])   # n ^3L_L
        m1 = same_j_mix(s1)
        m3 = same_j_mix(s3)
        theta = m1.mixing_angle_deg
        push!(results, (
            sector = sec.label,
            nL = string(n, L),
            paper = paper,
            theta = theta,
            delta = theta - paper,
            comp = complement_deg(theta),
            comp_delta = complement_deg(theta) - paper,
            diag_s = m1.unmixed_GeV,           # ^1L_L corrected (pre-mixing) mass
            diag_t = m3.unmixed_GeV,           # ^3L_L corrected (pre-mixing) mass
            split_MeV = 1000 * (m1.unmixed_GeV - m3.unmixed_GeV),
            offdiag_MeV = 1000 * m1.offdiag_GeV,
            low = m1.partner_masses_GeV[1],
            high = m1.partner_masses_GeV[2],
            src = sec.src,
        ))
    end
end

# --- report ------------------------------------------------------------------

outpath = joinpath(root, "docs", "residual_reports", "mixing_angles.md")
open(outpath, "w") do io
    println(io, "# Same-J Mixing-Angle Audit (13 text-quoted angles)")
    println(io)
    println(io, "Generated by `scripts/audit_mixing_angles.jl` on ",
        Dates.format(Dates.now(), "yyyy-mm-dd"), ".")
    println(io, numerics_provenance(FiniteDifferenceSolver()))
    println(io)
    println(io, "Computed-vs-paper comparison of every same-J `(^1L_L, ^3L_L)` mixing angle")
    println(io, "quoted in the text of Godfrey & Isgur, Phys. Rev. D 32, 189 (1985):")
    println(io, "strange (Fig. 4 caption), charmed (Fig. 7 caption), and b-flavored")
    println(io, "(Fig. 9 caption) sectors. Model angles come from the public spectrum API")
    println(io, "(`compute_spectrum` at production solver settings `ngrid = 450`,")
    println(io, "`rmax = 24.0`; `StateMixing` records with mechanism")
    println(io, "`antisymmetric_spin_orbit`), quark masses `u/d 0.220`, `s 0.419`,")
    println(io, "`c 1.628`, `b 4.977` GeV from `data/parameters.provisional.toml`.")
    println(io)
    println(io, "## Convention mapping (derived once, applied uniformly)")
    println(io)
    println(io, "The paper prints the same rotation matrix in all three captions:")
    println(io)
    println(io, "```")
    println(io, "[ Q_low  ]   [  cos(theta_nL)  sin(theta_nL) ] [ n ^1L_L ]")
    println(io, "[ Q_high ] = [ -sin(theta_nL)  cos(theta_nL) ] [ n ^3L_L ]")
    println(io, "```")
    println(io)
    println(io, "so the *lower-mass* eigenstate is")
    println(io, "`Q_low = cos(theta) |n ^1L_L> + sin(theta) |n ^3L_L>` with `cos(theta) >= 0`")
    println(io, "implied by the quoted range.")
    println(io)
    println(io, "Our `same_j_mixing` (`src/spin_fine_structure.jl`) diagonalizes the 2x2")
    println(io, "block `[E(^1L_L) c; c E(^3L_L)]` in the same `(singlet, triplet)` basis")
    println(io, "order, takes the eigenvector of the *lower* eigenvalue, normalizes its")
    println(io, "singlet component `>= 0`, and reports `theta = atan2(v_triplet, v_singlet)`,")
    println(io, "i.e. `low = cos(theta) ^1L_L + sin(theta) ^3L_L`, `theta` in `(-90, 90]`.")
    println(io, "That is definition-identical to the paper's, so")
    println(io)
    println(io, "> **theta_paper = theta_model (identity mapping; no transformation applied to any row).**")
    println(io)
    println(io, "Two residual sign conventions enter only through the off-diagonal element")
    println(io, "`c` and are pinned once, globally:")
    println(io)
    println(io, "1. **Constituent ordering.** `Meson(mq, f1, f2)` is the `f1 f2bar` meson;")
    println(io, "   the antisymmetric spin-orbit operator carries `(1/m1^2 - 1/m2^2)/2` and")
    println(io, "   flips sign under quark <-> antiquark exchange. Flavors are ordered")
    println(io, "   exactly as the paper's sector labels: `u sbar`, `c ubar`, `c sbar`,")
    println(io, "   `b ubar`, `b sbar`, `b cbar`.")
    println(io, "2. **Basis phase.** The angular matrix element is")
    println(io, "   `<^1L_L| L.(S1-S2) |^3L_L> = +sqrt(L(L+1))` with `S1` the quark (`f1`)")
    println(io, "   spin (`spin_orbit_mixing_components`, `src/spin_fine_structure.jl`).")
    println(io)
    println(io, "Consistency check (an outcome, not a fit): with this fixed mapping the")
    println(io, "model reproduces the paper's sector-wide sign pattern from the mass")
    println(io, "ordering alone — strange (`u` quark, heavy antiquark) angles positive,")
    println(io, "charmed (heavy quark, light antiquark) angles negative.")
    println(io)
    println(io, "## Computed vs paper")
    println(io)
    println(io, "Both columns use the paper convention above. `Delta = computed - paper`.")
    println(io)
    println(io, "| Sector | nL | Computed theta (deg) | Paper theta (deg) | Delta (deg) |")
    println(io, "|---|---|---:|---:|---:|")
    for r in results
        @printf(io, "| %s | %s | %+.1f | %+.0f | %+.1f |\n",
            r.sector, r.nL, r.theta, r.paper, r.delta)
    end
    println(io)
    println(io, "## Notes on deviations")
    println(io)
    println(io, "- **`b ubar`/`b sbar`/`b cbar` 1P (apparent ~90-deg disagreements).** In these")
    println(io, "  blocks the singlet/triplet diagonals are nearly degenerate")
    for r in results
        startswith(r.sector, "b ") || continue
        @printf(io, "  (`%s`: split %+.1f MeV vs offdiag %+.1f MeV)",
            r.sector, r.split_MeV, r.offdiag_MeV)
        println(io, r.sector == "b cbar" ? "," : ";")
    end
    println(io, "  and our lower eigenvalue carries the combination the paper labels as")
    println(io, "  `Q_high`. Quoting the complementary angle — the exact same eigenvectors")
    println(io, "  with the low/high labels exchanged, `theta -> theta - 90` — gives")
    bnotes = String[]
    for r in results
        startswith(r.sector, "b ") || continue
        push!(bnotes, @sprintf("`%s` %+.1f vs paper %+.0f (Delta %+.1f)",
            r.sector, r.comp, r.paper, r.comp_delta))
    end
    println(io, "  ", join(bnotes, ", "), ".")
    println(io, "  So the mixing *content* agrees to 1-5 deg; what differs is which of the")
    println(io, "  two nearly degenerate eigenstates is lower. This matches the earlier")
    println(io, "  `b cbar` diagnostic in `heavy_quarkonium_diagnostics.md` (+42.1 deg,")
    println(io, "  complement -47.9 deg, vs paper -53 deg).")
    println(io, "- **`c sbar` 1P (-14.2 vs -44, largest miss) and `c ubar` 1P (-24.8 vs -41).**")
    println(io, "  The 1P off-diagonals are only 1-2 MeV here, so")
    println(io, "  `theta = atan(2c / (E_s - E_t)) / 2`-type sensitivity makes the angle")
    println(io, "  hostage to the few-MeV singlet-triplet splitting; our splittings are")
    println(io, "  larger relative to `c` than the paper's effective ones.")
    println(io, "- **`u sbar` 1P (+19.5 vs +34, the K1 block) and 2P (+28.4 vs +15).** Same")
    println(io, "  small-off-diagonal sensitivity (|c| ~ 4-6 MeV). Note the trend inversion:")
    println(io, "  the paper's angles *decrease* with radial excitation (34 -> 15 for P,")
    println(io, "  33 -> 25 for D) while ours *increase* (19.5 -> 28.4, 32.7 -> 34.1).")
    println(io, "- **`u sbar` 2D (+34.1 vs +25) and 1G (+38.8 vs +33).** Milder (5-9 deg)")
    println(io, "  versions of the same pattern.")
    println(io, "- Blocks with large off-diagonals agree well: both 1D charm rows within")
    println(io, "  2.5 deg, strange 1D within 0.3 deg, strange 1F within 4.7 deg.")
    println(io)
    println(io, "## Diagnostics (raw block data)")
    println(io)
    println(io, "Corrected (pre-mixing) diagonal masses `E_s = E(^1L_L)`, `E_t = E(^3L_L)`,")
    println(io, "off-diagonal `c`, mixed eigenvalues, our raw angle, and the complementary")
    println(io, "angle (low/high labels exchanged). All angles already in the paper")
    println(io, "convention (identity mapping).")
    println(io)
    println(io, "| Sector | nL | E_s (GeV) | E_t (GeV) | E_s - E_t (MeV) | offdiag c (MeV) | low (GeV) | high (GeV) | theta (deg) | complement (deg) |")
    println(io, "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in results
        @printf(io,
            "| %s | %s | %.4f | %.4f | %+.2f | %+.2f | %.4f | %.4f | %+.2f | %+.2f |\n",
            r.sector, r.nL, r.diag_s, r.diag_t, r.split_MeV, r.offdiag_MeV,
            r.low, r.high, r.theta, r.comp)
    end
    println(io)
    println(io, "## Paper sources")
    println(io)
    for sec in sectors
        println(io, "- `", sec.label, "`: ", sec.src, ".")
    end
end

println("wrote ", outpath)
println()
@printf("%-8s %-3s %10s %8s %8s %12s\n",
    "sector", "nL", "computed", "paper", "delta", "complement")
for r in results
    @printf("%-8s %-3s %+10.1f %+8.0f %+8.1f %+12.1f\n",
        r.sector, r.nL, r.theta, r.paper, r.delta, r.comp)
end
