#!/usr/bin/env julia
# =============================================================================
# Paper-manifest checker — the anti-drift gate
# =============================================================================
# Globs docs/paper_manifest/*.toml, validates that every cited code symbol /
# test / report / page-image actually exists, rolls status up per section, and
# writes docs/residual_reports/manifest_check.md. Exits nonzero on any broken
# link so it can gate CI (scripts/verify_project.sh).
#
# Uses only Julia stdlib (TOML, Printf) — no project activation needed.

using TOML
using Printf

const ROOT = dirname(dirname(dirname(abspath(@__FILE__))))   # scripts -> GIPaper -> repo
const MANIFEST_DIR = joinpath(ROOT, "docs", "paper_manifest")
const REPORT = joinpath(ROOT, "GIPaper", "docs", "residual_reports", "manifest_check.md")
const RUNTESTS = joinpath(ROOT, "test", "runtests.jl")

const STATUSES = Set(["reproduced", "partial", "implemented", "folded", "context", "missing", "todo"])
const KINDS = Set(["equation", "table", "figure", "section", "input", "fit"])

# repo-relative path -> absolute; check existence
exists_rel(p) = isfile(joinpath(ROOT, p))

# "file:symbol" or "file" -> (file, symbol|nothing)
function split_code_ref(ref)
    parts = split(ref, ':')
    length(parts) == 1 ? (parts[1], nothing) : (join(parts[1:end-1], ':'), parts[end])
end

function load_units()
    units = Dict{String,Any}[]
    for f in sort(readdir(MANIFEST_DIR))
        endswith(f, ".toml") || continue
        data = TOML.parsefile(joinpath(MANIFEST_DIR, f))
        for u in get(data, "unit", Any[])
            u["_file"] = f
            push!(units, u)
        end
    end
    return units
end

function main()
    units = load_units()
    ids = Set(u["id"] for u in units)
    runtests = isfile(RUNTESTS) ? read(RUNTESTS, String) : ""
    # cache file contents for symbol checks
    filecache = Dict{String,String}()
    readcached(p) = get!(filecache, p) do
        exists_rel(p) ? read(joinpath(ROOT, p), String) : ""
    end

    problems = Tuple{String,String}[]   # (unit id, message)
    seen = Set{String}()
    for u in units
        id = u["id"]
        id in seen && push!(problems, (id, "duplicate id (also in another fragment)"))
        push!(seen, id)
        get(u, "status", "") in STATUSES || push!(problems, (id, "unknown status `$(get(u,"status",""))`"))
        get(u, "kind", "") in KINDS || push!(problems, (id, "unknown kind `$(get(u,"kind",""))`"))

        # code[]: file must exist; symbol (if given) must occur in it
        for ref in get(u, "code", String[])
            file, sym = split_code_ref(ref)
            if !exists_rel(String(file))
                push!(problems, (id, "code file missing: `$file`"))
            elseif sym !== nothing && !occursin(String(sym), readcached(String(file)))
                push!(problems, (id, "symbol `$sym` not found in `$file`"))
            end
        end
        # tests[]: name must occur in runtests.jl
        for t in get(u, "tests", String[])
            occursin(String(t), runtests) || push!(problems, (id, "test `$t` not found in test/runtests.jl"))
        end
        # report / anchor: file must exist (if given)
        for key in ("report", "anchor")
            p = get(u, key, "")
            isempty(p) || exists_rel(String(p)) || push!(problems, (id, "$key missing: `$p`"))
        end
        # parent must be "" or an existing id
        par = get(u, "parent", "")
        (isempty(par) || par in ids) || push!(problems, (id, "parent `$par` is not a known unit id"))
    end

    # --- rollup by section ---------------------------------------------------
    sections = [u for u in units if get(u, "kind", "") == "section"]
    childstatus(secid) = [get(u, "status", "todo") for u in units if get(u, "parent", "") == secid]
    function derived(statuses)
        isempty(statuses) && return "todo"
        all(s -> s in ("reproduced", "folded", "context"), statuses) && return "reproduced"
        any(s -> s in ("reproduced", "implemented", "partial"), statuses) && return "partial"
        return "todo"
    end

    open(REPORT, "w") do io
        println(io, "# Paper Manifest Check")
        println(io)
        println(io, "Generated by `julia GIPaper/scripts/check_manifest.jl`. Validates that every")
        println(io, "cited code symbol / test / report / page image in `docs/paper_manifest/*.toml`")
        println(io, "resolves, and rolls status up per section.")
        println(io)
        println(io, @sprintf("**%d units across %d fragments; %d broken links.**",
            length(units), length(unique(u["_file"] for u in units)), length(problems)))
        println(io)
        println(io, "## Broken links")
        println(io)
        if isempty(problems)
            println(io, "None — every reference resolves.")
        else
            for (id, msg) in problems
                println(io, "- `", id, "`: ", msg)
            end
        end
        println(io)
        println(io, "## Section rollup")
        println(io)
        println(io, "| section | units | reproduced | partial | implemented | folded | context | todo/missing | derived |")
        println(io, "|---|---:|---:|---:|---:|---:|---:|---:|:-:|")
        cnt(ss, s) = count(==(s), ss)
        for sec in sort(sections, by = s -> s["id"])
            ss = childstatus(sec["id"])
            println(io, @sprintf("| %s | %d | %d | %d | %d | %d | %d | %d | %s |",
                sec["label"], length(ss), cnt(ss, "reproduced"), cnt(ss, "partial"),
                cnt(ss, "implemented"), cnt(ss, "folded"), cnt(ss, "context"),
                cnt(ss, "todo") + cnt(ss, "missing"), derived(ss)))
        end
    end

    @printf("manifest: %d units, %d fragments, %d broken links -> %s\n",
        length(units), length(unique(u["_file"] for u in units)), length(problems), REPORT)
    for (id, msg) in problems
        println("  BROKEN  ", id, ": ", msg)
    end
    exit(isempty(problems) ? 0 : 1)
end

main()
