#!/usr/bin/env julia
# Replay recorded native waves; replace only the parent mixing coefficients.
# Run trace_rate_inputs.jl first when refreshing the underlying spectra.
using GIModel, QuarkModelTransitions, CSV, TOML, Printf, LinearAlgebra, SHA

root = dirname(@__DIR__)
tracepath = joinpath(root, "docs/input_traces/table_vi.toml")
referencepath = joinpath(root, "data/clean/mixings.csv")
trace = TOML.parsefile(tracepath)
refs = collect(CSV.File(referencepath))
_, masses = load_parameters_and_quark_masses(default_parameters_path())
names = Dict("eta_r" => "eta_r(?)", "etaprime_r" => "eta_r_prime(?)")
basisname(c) = string(c["basis"]["n"], " ",
    Dict("q" => "ns", "s" => "ss", "c" => "cc", "b" => "bb")[c["basis"]["flavors"][1]])
function wave(c)
    w = c["wave"]
    @assert w["representation"] == "HO"
    OscillatorWave(w["L"], w["beta_GeV"], w["coefficients"])
end

output = joinpath(root, "docs/investigations/excited_eta_moment_results.md")
open(output, "w") do io
    println(io, "# Excited-eta M1 composition substitution\n")
    println(io, "Generated by `julia --project=GIPaper/scripts GIPaper/scripts/investigate_excited_eta_moments.jl`.\n")
    println(io, "Native HO waves are replayed from the input trace. Only the parent's seven P1 coefficients are replaced by the printed Table III vector, shown both literally and normalized. Daughter composition, waves, charges and operator remain fixed. This is a diagnostic substitution, not a fitted prediction.\n")
    println(io, "| Transition | Native μN | Printed coefficients μN | Normalized coefficients μN | GI μN | Σabs(terms)/abs(sum) | Printed vector norm |\n|---|---:|---:|---:|---:|---:|---:|")
    count = 0
    for row in trace["rows"]
        kind, parent, daughter = row["id"]
        kind == "M1" && haskey(names, parent) && daughter in ("rho", "omega", "phi") || continue
        @assert !row["recoil_c"] && row["recoil_g_beta_GeV"] == "unused"
        pc, dc = row["parent_components"], row["daughter_components"]
        reference = Dict(String(r.basis) => r.amplitude for r in refs
            if isequal(r.model, "P1") && r.state_name == names[parent])
        paper = [reference[basisname(c)] for c in pc]
        paper_norm = norm(paper)
        paper ./= paper_norm
        terms, substituted = Float64[], Float64[]
        for (i, p) in enumerate(pc), d in dc
            p["basis"]["flavors"] == d["basis"]["flavors"] || continue
            f = p["basis"]["flavors"][1]
            m = masses[f]
            charge = neutral_m1_charge(Symbol(f);
                isovector_left = row["isovector_parent"],
                isovector_right = row["isovector_daughter"])
            kernel = m1_transition_moment(momentum_wave(wave(p)), momentum_wave(wave(d)),
                m, m, [(charge, m)])
            push!(terms, p["coefficient"] * d["coefficient"] * kernel)
            push!(substituted, paper[i] * d["coefficient"] * kernel)
        end
        value = sum(terms)
        @assert isapprox(value, row["computed"]; atol=1e-9, rtol=1e-8)
        @printf(io, "| %s → %s | %+.6f | %+.6f | %+.6f | %+.6f | %.2f | %.6f |\n",
            parent, daughter, value, sum(substituted)*paper_norm, sum(substituted), row["comparison_only"]["paper"],
            sum(abs, terms)/abs(value), paper_norm)
        count += 1
    end
    @assert count == 6
    basis = ["1 ns", "1 ss", "1 cc", "1 bb", "2 ns", "2 ss", "2 cc"]
    lightnames = ["eta(548)", "eta_prime(958)", "eta_r(?)", "eta_r_prime(?)"]
    vectors = [Float64[only(r.amplitude for r in refs if isequal(r.model, "P1") &&
        r.state_name == name && r.basis == b) for b in basis] for name in lightnames]
    gram = hcat(vectors...)' * hcat(vectors...)
    println(io, "\n## Printed P1 vector consistency\n")
    println(io, "| Pair | Raw inner product |\n|---|---:|")
    for i in 1:4, j in i:4
        @printf(io, "| %s / %s | %.6f |\n", lightnames[i], lightnames[j], gram[i,j])
    end
    println(io, "\nDistinct eigenvectors of one real symmetric matrix in an orthonormal basis must be orthogonal. These printed P1 columns do not satisfy that condition. Their interpretation must be resolved before demanding simultaneous mass-and-component agreement from such a matrix. This check does not establish whether the source uses a different convention, a different construction, or contains a table error.\n")
    println(io, "\nAll six replayed moments agree with the original trace to 1e-9 absolute / 1e-8 relative tolerance. None consumes photon momentum: the modern/historical q change has exactly zero effect on these moments. Widths still depend on q³. The cancellation measure describes the native decomposition, not an uncertainty estimate.\n")
    println(io, "Input SHA-256: trace `", bytes2hex(sha256(read(tracepath))), "`; mixing references `", bytes2hex(sha256(read(referencepath))), "`.")
end
println("wrote ", output)
