#!/usr/bin/env julia
using TOML, CSV, LinearAlgebra, Printf, SHA

root = dirname(@__DIR__)
tracepath = joinpath(root, "docs/input_traces/table_vii.toml")
refpath = joinpath(root, "data/clean/mixings.csv")
trace = TOML.parsefile(tracepath)
refs = collect(CSV.File(refpath))
rows = Dict(r["result"]["label"] => r["result"] for r in trace["two_photon"])
nn, ss = rows["f -> gamma gamma"], rows["f' -> gamma gamma"]
output = joinpath(root, "docs/investigations/tensor_photon_results.md")
open(output, "w") do io
    println(io, "# Tensor two-photon flavor substitution\n")
    println(io, "Generated by `julia --project=GIPaper/scripts GIPaper/scripts/investigate_tensor_photons.jl`.\n")
    println(io, "Uses the canonical central-wave amplitudes and their exact M^(3/2) dependence. Each flavor contribution is evaluated at the same final-state mass before adding normalized printed Table III light-flavor coefficients. Heavy admixtures are omitted; this is a two-flavor diagnostic, not the full mixed fixed-sector prediction. No parameter is fitted.\n")
    println(io, "| State | Ideal | nn contribution | ss contribution | Mixed | GI | Fraction of absolute residual removed |\n|---|---:|---:|---:|---:|---:|---:|")
    for (name, row) in (("f2(1270)", nn), ("f2_prime(1515)", ss))
        ref = Dict(String(r.basis) => r.amplitude for r in refs
            if r.state_name == name && r.state_group == "1 3P2")
        cs = [ref["1 ns"], ref["1 ss"]]
        cs ./= norm(cs)
        a = cs[1] * nn["model"] * (row["M"]/nn["M"])^1.5
        b = cs[2] * ss["model"] * (row["M"]/ss["M"])^1.5
        mixed = a+b
        removed = 1 - abs(mixed-row["paper"])/abs(row["model"]-row["paper"])
        @printf(io, "| %s | %+.6f | %+.6f | %+.6f | %+.6f | %+.6f | %.1f%% |\n",
            name, row["model"], a, b, mixed, row["paper"], 100removed)
    end
    println(io, "\nAmplitudes in keV^(1/2). A negative removed fraction means the diagnostic worsens agreement. For an already matching row this percentage is ill-conditioned; use absolute amplitudes.\n")
    println(io, "Trace SHA-256 `", bytes2hex(sha256(read(tracepath))), "`; references `", bytes2hex(sha256(read(refpath))), "`.")
end
println("wrote ", output)
