# Included by investigate_mixing_composition.jl --report: merges the before/after
# CSV ledgers into mixing_composition_results.md and the critical figure.
using CairoMakie

rd(name) = DataFrame(CSV.File(joinpath(out, name)))
A0, A1 = rd("angles_before.csv"), rd("angles_after.csv")
T0, T1 = rd("tensor_before.csv"), rd("tensor_after.csv")
G0, G1 = rd("global_before.csv"), rd("global_after.csv")
S2, VAR = rd("stage2_after.csv"), rd("variants_after.csv")
stage1 = [(n, rd("angles_after_$n.csv")) for n in ("fd900", "fd600_rmax32", "ho", "ho_nbasis6_unconverged")]
docs = joinpath(root, "docs", "investigations")
fmt(x, f = "%+.1f") = ismissing(x) ? "–" : Printf.format(Printf.Format(f), x)

# ---------------------------------------------------------------- figure
before, after, ink = colorant"#eb6834", colorant"#2a78d6", colorant"#52514e"
fig = Figure(size = (1500, 500), fontsize = 15)
pairs0, pairs1 = filter(r -> !ismissing(r.gap_GI), A0), filter(r -> !ismissing(r.gap_GI), A1)
ax1 = Axis(fig[1, 1], xlabel = "GI two-state gap E(¹L_L) − E(³L_L)  (MeV)", ylabel = "GIModel fixed-sector gap (MeV)",
    title = "(a) Diagonal singlet–triplet gap: the cause")
lines!(ax1, [-35, 35], [-35, 35], color = (ink, 0.5), linestyle = :dash)
scatter!(ax1, pairs0.gap_GI, pairs0.gap, color = :white, strokecolor = before, strokewidth = 2, markersize = 12, label = "S-wave-only contact (before)")
scatter!(ax1, pairs1.gap_GI, pairs1.gap, color = after, markersize = 12, label = "contact in all L (after)")
for r in eachrow(pairs1)   # the three high-L kaon pairs overlap; label them once
    r.nL in ("1D", "1F", "1G") && continue
    text!(ax1, r.gap_GI, r.gap, text = r.sector * " " * r.nL, fontsize = 11, color = ink, offset = (6, -4))
end
text!(ax1, -12.5, -12, text = "us 1D, 1F, 1G", fontsize = 11, color = ink, offset = (8, 6))
axislegend(ax1, position = :lt, labelsize = 12, framevisible = false)
ax2 = Axis(fig[1, 2], xlabel = "GI lower-state singlet probability cos²θ", ylabel = "GIModel", limits = (0, 1, 0, 1),
    title = "(b) All 13 published compositions")
lines!(ax2, [0, 1], [0, 1], color = (ink, 0.5), linestyle = :dash)
for (a, b) in zip(eachrow(A0), eachrow(A1))
    lines!(ax2, [a.singlet_GI, b.singlet_GI], [a.singlet, b.singlet], color = (ink, 0.25))
end
scatter!(ax2, A0.singlet_GI, A0.singlet, color = :white, strokecolor = before, strokewidth = 2, markersize = 11)
scatter!(ax2, A1.singlet_GI, A1.singlet, color = after, markersize = 11)
ax3 = Axis(fig[1, 3], xlabel = "|V| from GI masses + angle (MeV)", ylabel = "|V| GIModel (MeV)", xscale = log10, yscale = log10,
    limits = (0.5, 40, 0.5, 40), xticks = [1, 2, 5, 10, 20], yticks = [1, 2, 5, 10, 20], title = "(c) Off-diagonal: unresolved remainder")
lines!(ax3, [0.5, 40], [0.5, 40], color = (ink, 0.5), linestyle = :dash)
scatter!(ax3, abs.(pairs0.V_GI), abs.(pairs0.V), color = :white, strokecolor = before, strokewidth = 2, markersize = 12)
scatter!(ax3, abs.(pairs1.V_GI), abs.(pairs1.V), color = after, markersize = 12)
for r in eachrow(pairs1)
    left = r.nL in ("1P",) && r.sector == "cs"
    text!(ax3, abs(r.V_GI), abs(r.V), text = r.sector * " " * r.nL, fontsize = 11, color = ink,
        offset = left ? (4, -8) : (7, -4), align = left ? (:left, :top) : (:left, :bottom))
end
Label(fig[2, 1:3], "FD ngrid=450, rmax=24 GeV⁻¹. GI gap/V: conditional two-state inversion of printed (10 MeV) masses and caption angles; dashed = equality.",
    fontsize = 12, color = ink)
save(joinpath(docs, "figures", "mixing_composition_cause.png"), fig)
save(joinpath(docs, "figures", "mixing_composition_cause.svg"), fig)

# ---------------------------------------------------------------- results note
io = IOBuffer()
p(x...) = println(io, x...)
p("# Mixing-composition investigation: numerical results\n")
p("**Closed:** the all-L contact bug is fixed; the remaining large same-J GI85 caption mismatch is a historical reference discrepancy. Original numerical comparisons below are retained. See the [current GI85/GK91 benchmark](../residual_reports/mixing_angles.md). The separate ψ(3.82) tensor question remains open.\n")
p("Generated by `GIPaper/scripts/investigate_mixing_composition.jl --report` from the CSV ledgers in ",
  "[`mixing_composition/`](mixing_composition/). *Before* = GIModel 88e9a99 (contact term only in S waves); ",
  "*after* = contact term in every L (this investigation). Narrative and conclusions: ",
  "[mixing_composition_investigation.md](mixing_composition_investigation.md).\n")
p("![cause](figures/mixing_composition_cause.png)\n")
p("## 13 spin–orbit compositions (paper convention Q_low = cosθ ¹L_L + sinθ ³L_L)\n")
p("P_s = lower-state singlet probability projected on the same-n pair; out = norm outside that pair; ",
  "dist = angular distance mod 180° without low/high exchange.\n")
p("| Sector | nL | GI θ | GI P_s | θ before | P_s before | θ after | P_s after | out % after | dist before | dist after |")
p("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
for (a, b) in zip(eachrow(A0), eachrow(A1))
    p("| $(b.sector) | $(b.nL) | $(fmt(b.theta_GI, "%+.0f")) | $(fmt(b.singlet_GI, "%.3f")) | $(fmt(a.theta)) | $(fmt(a.singlet, "%.3f")) | ",
      "$(fmt(b.theta)) | $(fmt(b.singlet, "%.3f")) | $(fmt(100b.outside, "%.3f")) | $(fmt(a.distance, "%.1f")) | $(fmt(b.distance, "%.1f")) |")
end
p("\nMedian angular distance: before $(fmt(median(A0.distance), "%.1f"))°, after $(fmt(median(A1.distance), "%.1f"))°. ",
  "Rows within 6°: before $(count(<(6), A0.distance))/13, after $(count(<(6), A1.distance))/13.\n")
p("## Block ingredients and masses (MeV)\n")
p("gap = E(¹L_L) − E(³L_L) of the fixed-sector (pre-mixing) masses; V = same-n antisymmetric element; ",
  "S = P-wave-type contact strength ⟨(32π/9m₁m₂) F δ̃ F⟩ on the singlet wave (¹L_L gets −3S/4, ³L_L +S/4). ",
  "GI gap/V are a conditional two-state inversion of printed masses and angle, available for 8 rows.\n")
p("| Sector | nL | gap GI | gap before | gap after | V GI | V before | V after (vector / Thomas) | S after | low/high GI | low/high after |")
p("|---|---|---:|---:|---:|---:|---:|---|---:|---|---|")
for (a, b) in zip(eachrow(A0), eachrow(A1))
    p("| $(b.sector) | $(b.nL) | $(fmt(b.gap_GI)) | $(fmt(a.gap)) | $(fmt(b.gap)) | $(fmt(b.V_GI)) | $(fmt(a.V, "%+.2f")) | ",
      "$(fmt(b.V, "%+.2f")) ($(fmt(b.V_vector, "%+.1f")) / $(fmt(b.V_thomas, "%+.1f"))) | $(fmt(b.contact_S_singlet)) | ",
      "$(ismissing(b.low_GI) ? "–" : "$(b.low_GI)/$(b.high_GI)") | $(fmt(b.low, "%.0f"))/$(fmt(b.high, "%.0f")) |")
end
p("\n## Tensor compositions (amplitudes relative to the dominant component)\n")
p("GI prints rounded amplitudes, not probabilities; relative signs depend on the radial phase convention. ",
  "`origin+` = each radial wave positive at r→0 (GIModel stores outer-lobe-positive waves). ",
  "Second-stage basis: 1–5 ³S₁ and 1–3 ³D₁.\n")
p("| State | component | GI | before (origin+) | after (origin+) | after (outer+) |")
p("|---|---|---:|---:|---:|---:|")
for (a, b) in zip(eachrow(T0), eachrow(T1))
    (ismissing(b.GI) && abs(b.amplitude_origin) < 0.003) && continue
    p("| $(b.state) ($(fmt(a.mass, "%.0f"))→$(fmt(b.mass, "%.0f")) MeV) | $(b.component) | $(fmt(b.GI, "%+.2f")) | ",
      "$(fmt(a.amplitude_origin, "%+.4f")) | $(fmt(b.amplitude_origin, "%+.4f")) | $(fmt(b.amplitude_outer, "%+.4f")) |")
end
p("\n## Spectrum-wide test (independent of mixing)\n")
p("Residual = GIModel − GI printed mass over all seven `reference_spectrum_*.csv` catalogs ",
  "(canonical `compare_reference`, reference-order assignment). The missing term predicts a positive bias ",
  "for L>0 singlets and a negative one for L>0 triplets.\n")
p("| Subset | n | mean residual before | mean residual after | mean abs before | mean abs after |")
p("|---|---:|---:|---:|---:|---:|")
subsets = [("all", r -> true), ("L = 0", r -> r.L == "S"), ("L > 0", r -> r.L != "S")]
for L in ("P", "D", "F", "G"), m in (1, 3)
    push!(subsets, ("L = $L, 2S+1 = $m", r -> r.L == L && r.multiplicity == m))
end
for c in sort(unique(G1.catalog))
    push!(subsets, ("$c, L > 0", r -> r.catalog == c && r.L != "S"))
end
for (name, f) in subsets
    a, b = filter(f, G0), filter(f, G1)
    nrow(a) == 0 && continue
    p("| $name | $(nrow(a)) | $(fmt(mean(a.residual))) | $(fmt(mean(b.residual))) | $(fmt(mean(abs.(a.residual)), "%.1f")) | $(fmt(mean(abs.(b.residual)), "%.1f")) |")
end
p("\n## Stage-1 convergence (fixed-sector radial problem), after\n")
p("| Sector | nL | FD 450/24 | FD 900/24 | FD 600/32 | HO adaptive | HO nbasis=6, unconverged |")
p("|---|---|---:|---:|---:|---:|---:|")
for (i, b) in enumerate(eachrow(A1))
    p("| $(b.sector) | $(b.nL) | $(fmt(b.theta, "%+.2f")) | ", join([fmt(t[2].theta[i], "%+.2f") for t in stage1], " | "), " |")
end
p("\n## Stage-2 convergence (second-stage mixing basis), after, FD 450\n")
p("Lower-state angle for second-stage blocks truncated to N radial eigenstates per sector, and for the full ",
  "coupled-channel grid problem [H(¹L_L) W; W H(³L_L)] (the complete-basis limit). `out` = norm outside the same-n pair.\n")
bases = ["N = n", "N = n+1", "N = n+3", "N = 10", "N = 40", "coupled grid"]  # row order in stage2_rows
p("| Sector | nL | ", join(bases, " | "), " | out % (coupled) |")
p("|---|---|", repeat("---:|", length(bases) + 1))
for g in groupby(S2, [:sector, :nL]; sort = false)
    p("| $(g.sector[1]) | $(g.nL[1]) | ", join([fmt(t, "%+.2f") for t in g.theta], " | "),
      " | $(fmt(100g.outside[end], "%.3f")) |")
end
p("\n## Diagnostic substitutions in the antisymmetric element (not fixes)\n")
p("Ratio = V_GI / V_variant for the 8 mass-constrained pairs; a prescription GI could have used would give ratios ≈ 1 in every row.\n")
vs = unique(VAR.variant)
p("| Sector | nL | V_GI | ", join(vs, " | "), " |")
p("|---|---|---:|", repeat("---:|", length(vs)))
for g in groupby(VAR, [:sector, :nL]; sort = false)
    p("| $(g.sector[1]) | $(g.nL[1]) | $(fmt(g.V_GI[1])) | ",
      join(["$(fmt(only(g[g.variant .== v, :V]), "%+.1f")) (×$(fmt(only(g[g.variant .== v, :ratio]), "%.2f")))" for v in vs], " | "), " |")
end
write(joinpath(docs, "mixing_composition_results.md"), String(take!(io)))
println("wrote mixing_composition_results.md and figures/mixing_composition_cause.{png,svg}")
