#!/usr/bin/env julia

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."); io = devnull)

using CSV
using GIPaper
using Printf

const ROOT = dirname(@__DIR__)
const CLEAN = joinpath(ROOT, "data", "clean")
const REPORTS = joinpath(ROOT, "docs", "residual_reports")
const MODES = (:none, :calibrated_p1, :paper_p1, :paper_p2)

read_text(path) = isfile(path) ? read(path, String) : ""
read_rows(path) = isfile(path) ? collect(CSV.File(path; normalizenames = false)) : NamedTuple[]

function cell(row, name)
    value = getproperty(row, Symbol(name))
    return ismissing(value) ? "" : strip(string(value))
end

function threshold_points(value; full, partial)
    isnothing(value) && return 0
    value <= full && return 20
    value <= partial && return 10
    return 0
end

function formula_points()
    text = read_text(joinpath(ROOT, "docs", "formula_map.md"))
    lines = split(text, '\n')
    items = ("Eq. (16)", "Eq. (17)", "Eq. (18a)", "Eq. (18b)", "Table III")
    return 4 * count(items) do item
        any(lines) do line
            occursin(item, line) &&
                (occursin("image-audited", lowercase(line)) ||
                 occursin("implemented", lowercase(line)))
        end
    end
end

function clean_data_points()
    masses = read_rows(joinpath(CLEAN, "masses.csv"))
    n_isoscalar = count(masses) do row
        cell(row, "sector") == "isoscalar" &&
            cell(row, "L") == "S" &&
            cell(row, "S") == "0" &&
            cell(row, "J") == "0" &&
            cell(row, "n") in ("1", "2")
    end
    points = n_isoscalar >= 4 ? 10 : 0

    mixings = read_rows(joinpath(CLEAN, "mixings.csv"))
    audited_models = Set(
        cell(row, "model") for row in mixings
        if cell(row, "confidence") in ("high", "medium")
    )
    return points + (issubset(Set(("P1", "P2")), audited_models) ? 10 : 0)
end

function calibrated_mass_residual()
    residuals = Float64[]
    for line in split(read_text(joinpath(REPORTS, "isoscalar_residuals.md")), '\n')
        startswith(line, "| `") || continue
        stripped = strip(line)
        cells = strip.(split(stripped[2:end-1], '|'))
        length(cells) >= 4 || continue
        replace(cells[1], "`" => "") in ("1^1S_0", "2^1S_0") || continue
        residual = tryparse(Float64, replace(cells[4], "+" => ""))
        isnothing(residual) || push!(residuals, abs(residual))
        length(residuals) == 4 && break
    end
    return length(residuals) == 4 ? sum(residuals) / length(residuals) : nothing
end

function literal_audit_metrics()
    mixing_rms = Dict{String,Float64}()
    mass_residual = Dict{String,Float64}()
    text = read_text(joinpath(REPORTS, "table_iii_mixing_audit.md"))
    for line in split(text, '\n')
        match_rms = match(r"Mean vector RMS for `(P[12])`: `([0-9.]+)`", line)
        if !isnothing(match_rms)
            mixing_rms[match_rms.captures[1]] = parse(Float64, match_rms.captures[2])
        end
        match_mass =
            match(r"Mean abs mass residual for `(P[12])`: `([0-9.]+) MeV`", line)
        if !isnothing(match_mass)
            mass_residual[match_mass.captures[1]] =
                parse(Float64, match_mass.captures[2])
        end
    end
    return mixing_rms, mass_residual
end

function format_metric(value, digits)
    return isnothing(value) ? "n/a" : @sprintf("%.*f", digits, value)
end

function main()
    formula = formula_points()
    clean = clean_data_points()

    # The verification gate runs the behavioral tests before this script.
    # Implementation credit therefore comes from the package's declared,
    # validated dispatch surface instead of grepping source and test text.
    implementation =
        sum(5 for mode in MODES if mode in GIPaper.COMPARISON_ANNIHILATION_SCHEMES)

    calibrated = calibrated_mass_residual()
    mixing_rms, literal_mass = literal_audit_metrics()
    model_mass = Dict{Symbol,Float64}(
        :paper_p1 => get(literal_mass, "P1", NaN),
        :paper_p2 => get(literal_mass, "P2", NaN),
    )
    isnothing(calibrated) || (model_mass[:calibrated_p1] = calibrated)
    filter!(pair -> isfinite(last(pair)), model_mass)
    model_rms = Dict{Symbol,Float64}(
        :paper_p1 => get(mixing_rms, "P1", NaN),
        :paper_p2 => get(mixing_rms, "P2", NaN),
    )
    filter!(pair -> isfinite(last(pair)), model_rms)

    rows = map(MODES) do model
        mass = get(model_mass, model, nothing)
        rms = get(model_rms, model, nothing)
        spectral = threshold_points(mass; full = 25.0, partial = 50.0)
        mixing = threshold_points(rms; full = 0.20, partial = 0.35)
        total = formula + clean + implementation + spectral + mixing
        (; model, formula, clean, implementation, spectral, mixing, total, mass, rms)
    end

    mkpath(REPORTS)
    output = joinpath(REPORTS, "annihilation_model_scorecard.md")
    open(output, "w") do io
        println(io, "# Annihilation Model Scorecard")
        println(io)
        println(io, "Generated by `julia GIPaper/scripts/score_annihilation.jl`.")
        println(io)
        println(io, "| model | formula points | clean target points | implementation points | spectral points | mixing points | total points | mean abs mass residual MeV | mixing RMS error |")
        println(io, "|---|---:|---:|---:|---:|---:|---:|---:|---:|")
        for row in rows
            @printf(
                io,
                "| %s | %d | %d | %d | %d | %d | %d | %s | %s |\n",
                repr(row.model),
                row.formula,
                row.clean,
                row.implementation,
                row.spectral,
                row.mixing,
                row.total,
                format_metric(row.mass, 1),
                format_metric(row.rms, 3),
            )
        end
        println(io)
        println(io, "## Missing Points")
        println(io)
        println(io, "- Mixing points come from the mean Table III amplitude RMS in `table_iii_mixing_audit.md` (20 if <= 0.20, 10 if <= 0.35), evaluated on HO-basis wavefunctions with the Φ(0)>0 annihilation phase convention.")
        println(io, "- Spectral points use the same thresholds for every model (20 if mean abs residual <= 25 MeV, 10 if <= 50): the calibrated control is scored against the digitized Fig. 5 labels, the literal modes against the paper-model mass targets in `table_iii_mixing_audit.md`. Literal-mode mass residuals are reported there directly rather than attributed to an obsolete solver discrepancy.")
    end

    println("wrote docs/residual_reports/annihilation_model_scorecard.md")
    println("top score: ", maximum(row.total for row in rows), " / 100")
end

main()
