name = "GIPaper"
uuid = "49ec1c8d-b0ea-4dff-ad2d-05293f1534fc"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@gmail.com>"]
version = "0.1.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
GIModel = "7b2df1f2-6404-4fb8-a3f7-191b7dc823e0"
QuarkModelTransitions = "87282b95-dd94-4373-9910-f2158c0f9e5e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[sources]
GIModel = {path = ".."}
QuarkModelTransitions = {path = "../QuarkModelTransitions"}

[compat]
julia = "1.11"
Aqua = "0.8"
Test = "1.11"
CSV = "0.10.16"
GIModel = "0.4"
QuarkModelTransitions = "0.2"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
TOML = "1.0.3"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
