#!/usr/bin/env julia
# =============================================================================
# The E1 m/E exponent against measured radiative widths (GIModel.jl #28).
# =============================================================================
# GI 1985 multiply every electric radial moment E_n^i by |m_i/sqrt(<E_i><E_i>)|^p
# and fixed p = 0.5 on A2 -> pi gamma. Godfrey's later papers use p = 0. Here
# PhotonEmission is evaluated at p in [0, 1] on measured widths, in three groups:
#   heavy            charmonium and bottomonium E1 (p should hardly matter),
#   light_e1         allowed E1 with light emitters,
#   light_spin_flip  spin-flip E1/M2 with light emitters.
# Widths use GI wavefunctions and PDG 2026 masses for the photon momentum.

mkpath(joinpath(dirname(@__DIR__), "reports"))

using Pkg
Pkg.activate(dirname(@__DIR__); io = devnull)

using CSV, Printf
using GIModel
using GIModel.QuarkModelTransitions

const ROOT = dirname(@__DIR__)
params, mq = load_parameters_and_quark_masses(default_parameters_path())
solver = OscillatorSolver()
pdg = Dict(String(r.particle) => r.mass_MeV / 1000 for r in CSV.File(joinpath(ROOT, "data", "pdg_mesons_2026.csv")))
rows = collect(CSV.File(joinpath(ROOT, "data", "measured_radiative_widths.csv")))

# Pure S and P levels: the leading kernels reject S-D admixtures.
levels(n) = spectrum_levels(n; L_labels = ("S", "P"))
spectra = Dict(
    "cc" => compute_spectrum(params, Meson(mq, :c, :c); levels = levels(2), solver),
    "bb" => compute_spectrum(params, Meson(mq, :b, :b); levels = levels(3), solver),
    "ud" => compute_spectrum(params, Meson(mq, :u, :d); levels = levels(1), solver),
    "us" => compute_spectrum(params, Meson(mq, :u, :s); levels = levels(1), solver),
    "ds" => compute_spectrum(params, Meson(mq, :d, :s); levels = levels(1), solver),
)
# The component named by the row's label, at the PDG mass. A spectrum state lists
# every basis state of its sector (b1 carries a 3P1 component with coefficient
# 0), and PhotonEmission evaluates one kernel per transition, so each row is
# evaluated for that individual component, as the operator's error advises. The
# component keeps its coefficient (exactly 1 for every row here).
function labeled_component(spec, label, M)
    state = physical_state(spec, label)
    c = only(c for c in state.components if
             string(c.basis.n, "^", c.basis.multiplicity, c.basis.L_label, "_", c.basis.J) == label)
    return PhysicalState(state.label, M, [c])
end

# Ideally mixed nonstrange isoscalar (u ubar + d dbar)/sqrt 2 and the rho0
# (u ubar - d dbar)/sqrt 2, built from the n nbar waves.
function nonstrange(label, sign, M)
    c = argmax(c -> abs(c.coefficient), physical_components(spectra["ud"], label))
    PhysicalState(label, M, [(basis = BasisState(c.basis.n, c.basis.L_label, c.basis.multiplicity, c.basis.J;
                                  flavors = (f, f)), coefficient = s / sqrt(2), wave = c.wave)
                             for (f, s) in ((:u, 1.0), (:d, sign))])
end

function states(r)
    Mi, Mf = pdg[String(r.initial_pdg)], pdg[String(r.final_pdg)]
    if r.flavors == "isoscalar_to_rho"
        return nonstrange(String(r.initial_label), 1.0, Mi), nonstrange(String(r.final_label), -1.0, Mf)
    end
    spec = spectra[String(r.flavors)]
    return labeled_component(spec, String(r.initial_label), Mi),
           labeled_component(spec, String(r.final_label), Mf)
end
const STATES = Dict(r.decay => states(r) for r in rows)

width_keV(r, p) = 1000 * decay_width(matrix_element(STATES[r.decay][2],
    PhotonEmission(mq; electric_exponent = p), STATES[r.decay][1]))

# The full quark current (all multipoles, exact in q, spin-current E1 included).
exact_keV(r) = 1000 * decay_width(matrix_element(STATES[r.decay][2],
    MultipolePhotonEmission(mq), STATES[r.decay][1]))
exact = Dict(r.decay => exact_keV(r) for r in rows)

exponents = 0.0:0.05:1.0
widths = Dict((r.decay, p) => width_keV(r, p) for r in rows, p in exponents)
groups = ("heavy", "light_e1", "light_spin_flip")
function chi2(group, p)
    sum(((widths[(r.decay, p)] - r.width_keV) / r.error_keV)^2
        for r in rows if r.group == group && !r.upper_limit; init = 0.0)
end
npoints(group) = count(r -> r.group == group && !r.upper_limit, rows)
chi2_exact(group) = sum(((exact[r.decay] - r.width_keV) / r.error_keV)^2
    for r in rows if r.group == group && !r.upper_limit; init = 0.0)
best(group) = argmin(p -> chi2(group, p), exponents)

output = joinpath(ROOT, "reports", "radiative_exponent.md")
open(output, "w") do io
    println(io, "# The E1 m/E exponent against measured radiative widths")
    println(io, "\nGenerated by `checks/audit_radiative_exponent.jl`.")
    println(io, "\n", numerics_provenance(solver))
    println(io, """

    `PhotonEmission(mq; electric_exponent = p)` on measured widths (keV), GI
    wavefunctions, PDG 2026 masses for the photon momentum. Each state is the
    individual component named in the row (e.g. the 1^1P_1 component of b1),
    with its coefficient kept. GI 1985 use p = 0.5
    (fitted to A2 -> pi gamma with spin-flip denominators sqrt(2) too small);
    Godfrey's later papers use p = 0. Spin-flip kernels carry the corrected
    normalization (GIModel.jl #27). Errors are experimental only; the model has
    no error assigned, so chi^2 measures the pattern, not a goodness of fit.
    `full current` is `MultipolePhotonEmission` (p = 0, every multipole, exact
    in q), which adds the spin-current contribution to E1 that the leading
    kernels omit.
    """)
    println(io, "## Widths at p = 0 and p = 0.5\n")
    println(io, "| group | decay | data | p = 0 | p = 0.5 | full current | ratio p=0 | ratio p=0.5 | ratio full |")
    println(io, "|---|---|---:|---:|---:|---:|---:|---:|---:|")
    for r in rows
        w0, w5 = widths[(r.decay, 0.0)], widths[(r.decay, 0.5)]
        data = r.upper_limit ? @sprintf("< %.4g", r.width_keV) : @sprintf("%.4g ± %.2g", r.width_keV, r.error_keV)
        ratio(w) = r.upper_limit ? (w < r.width_keV ? "below limit" : "ABOVE limit") : @sprintf("%.2f", w / r.width_keV)
        @printf(io, "| %s | %s | %s | %.4g | %.4g | %.4g | %s | %s | %s |\n", r.group, r.decay, data, w0, w5,
            exact[r.decay], ratio(w0), ratio(w5), ratio(exact[r.decay]))
    end
    println(io, "\n## chi^2 per group against the exponent\n")
    println(io, "| p | " * join(("$g ($(npoints(g)))" for g in groups), " | ") * " |")
    println(io, "|---:|" * repeat("---:|", length(groups)))
    for p in exponents
        @printf(io, "| %.2f | %s |\n", p, join((@sprintf("%.1f", chi2(g, p)) for g in groups), " | "))
    end
    @printf(io, "| full current (p = 0) | %s |\n", join((@sprintf("%.1f", chi2_exact(g)) for g in groups), " | "))
    println(io, "\n## Hold-out\n")
    for (train, test) in (("light_e1", "light_spin_flip"), ("light_spin_flip", "light_e1"))
        p = best(train)
        @printf(io, "- Fit on %s: best p = %.2f (chi^2 %.1f). Predicts %s with chi^2 %.1f for %d points (at its own best p = %.2f: %.1f). Heavy chi^2 at that p: %.1f.\n",
            train, p, chi2(train, p), test, chi2(test, p), npoints(test), best(test), chi2(test, best(test)), chi2("heavy", p))
    end
    println(io, """

    ## Conclusion

    - Heavy quarkonium prefers p = 0 (chi^2 $(round(chi2("heavy", 0.0); digits = 1)) against
      $(round(chi2("heavy", 0.5); digits = 1)) at p = 0.5). The factor is not negligible for charm:
      |m_c/<E_c>|^0.5 lowers chi_cJ -> J/psi gamma by about 13%. Godfrey's later GI-model
      papers also use p = 0.
    - No single exponent describes both light groups. Allowed E1 prefers p <= 0 and
      stays about 3 times below data; spin flip prefers p = 0.2. Each fit fails the
      other group, so the factor does not have the form the data need.
    - The full quark current with no fitted factor describes the spin-flip widths
      (a2 -> pi gamma, K2* -> K gamma within errors) and halves the f1 -> rho gamma
      deficit. The leading kernels expand exp(-i q.r) to first order, which
      overshoots for light mesons (q r ~ 1); the exact Bessel functions supply the
      suppression that the 1985 m/E exponent and recoil form factor were
      approximating. b1 -> pi gamma (singlet, no spin current) remains about 4 times
      low, an open light-quark question.
    - For heavy quarkonium the full current is not better than the leading kernel at
      p = 0 (chi^2 $(round(chi2_exact("heavy"); digits = 1)) against $(round(chi2("heavy", 0.0); digits = 1))): its
      spin-current E1 term, of relative order E_gamma/m, raises chi_c0 and chi_c1 but
      lowers chi_c2 -> J/psi gamma and psi(2S) -> chi_c0 gamma. All heavy widths stay
      10-30% below data in either form.

    PhotonEmission therefore defaults to p = 0. The GI 1985 Table VI audit sets
    p = 0.5 explicitly to reproduce the paper. For light mesons,
    MultipolePhotonEmission is the better-founded choice.
    """)
end
println("wrote ", output)
