#!/usr/bin/env julia
# =============================================================================
# Unequal-mass E1 cross-check against Godfrey's later GI-model papers.
# =============================================================================
# GI 1985 Table VI has no E1 row with unequal constituent masses, so the paper
# cannot test the centre-of-mass weighting of the E1 dipole. Godfrey's later
# papers (B_c 2004, D/D_s 2016, B/B_s 2016) use the same GI wavefunctions and
# the effective charge <e> = (m_j e_i + m_i e_j)/(m_i+m_j) with the
# nonrelativistic E1 formula, without the 1985 (m/E)^0.5 factor.
#
# Here each row uses our 1P and 1S wavefunctions at the paper's masses, so the
# photon momentum is theirs. The `NR` column switches off the m/E factor
# (electric_exponent = 0) and is the like-for-like comparison. The `GI 1985`
# column keeps the 1985 default exponent 0.5 and is shown for reference.

mkpath(joinpath(dirname(@__DIR__), "reports"))

using Pkg
Pkg.activate(dirname(@__DIR__); io = devnull)

using CSV, Printf, Statistics
using GIModel
using GIModel.QuarkModelTransitions

const ROOT = dirname(@__DIR__)
params, mq = load_parameters_and_quark_masses(default_parameters_path())
rows = CSV.File(joinpath(ROOT, "data", "later_godfrey_e1_widths.csv"))
solver = OscillatorSolver()

spectra = Dict{Tuple{Symbol,Symbol},Any}()
at_mass(state, M) = PhysicalState(state.label, M, state.components)

results = map(rows) do row
    flavors = (Symbol(row.flavor1), Symbol(row.flavor2))
    spectrum = get!(spectra, flavors) do
        compute_spectrum(params, Meson(mq, flavors...);
            levels = spectrum_levels(1; L_labels = ("S", "P")), solver)
    end
    initial = at_mass(physical_state(spectrum, String(row.initial)), row.M_initial_GeV)
    final = at_mass(physical_state(spectrum, String(row.final)), row.M_final_GeV)
    width(exponent) = 1000 * decay_width(matrix_element(
        final, PhotonEmission(mq; electric_exponent = exponent), initial))
    (row = row, nr = width(0.0), gi1985 = width(0.5))
end

ratios = [r.nr / r.row.width_keV for r in results]
@assert all(r -> 0.98 < r < 1.02, ratios) "NR E1 widths disagree with the later GI papers"

output = joinpath(ROOT, "reports", "heavy_light_e1.md")
open(output, "w") do io
    println(io, "# Unequal-mass E1 widths against later GI-model papers")
    println(io, "\nGenerated by `checks/audit_heavy_light_e1.jl`.")
    println(io, "\n", numerics_provenance(solver))
    println(io, """

    GI 1985 Table VI has no unequal-mass E1 row. Godfrey's later papers use the
    same wavefunctions with the centre-of-mass effective charge
    <e> = (m_j e_i + m_i e_j)/(m_i+m_j) and the nonrelativistic E1 formula.
    Each row below uses our 1P and 1S waves at the paper's masses. `NR` sets
    the m/E exponent to zero, as those papers do; `GI 1985` keeps the default
    exponent 0.5 for reference. Widths are in keV.
    """)
    println(io, "| meson | transition | paper | NR | NR/paper | GI 1985 | source |")
    println(io, "|---|---|---:|---:|---:|---:|---|")
    for r in results
        @printf(io, "| %s | %s → %s | %.4g | %.4g | %.3f | %.4g | %s |\n",
            r.row.meson, r.row.initial, r.row.final, r.row.width_keV, r.nr,
            r.nr / r.row.width_keV, r.gi1985, r.row.source)
    end
    @printf(io, "\nNR/paper ranges from %.3f to %.3f over %d rows.\n",
        minimum(ratios), maximum(ratios), length(ratios))
end
println("wrote ", output)
