#!/usr/bin/env julia
# Recompute residual reports for all reference_spectrum_*.csv catalogs.

mkpath(joinpath(dirname(@__DIR__), "reports"))

using Pkg
Pkg.activate(dirname(@__DIR__))

using Dates
using Printf

using GIModel
using GIPaper

params, mq = load_parameters_and_quark_masses(GIPaper.model_parameters_path())
data_dir = GIPaper.paper_data_dir()
report_dir = joinpath(dirname(@__DIR__), "reports")
mkpath(report_dir)

# The one place the production solver settings are chosen; every report below
# records it verbatim, so a residual can be checked against the basis that made it.
# Paper reproductions use the original investigation's oscillator method.
solver = OscillatorSolver()

score_rows = NamedTuple[]

for fn in readdir(data_dir)
    startswith(fn, "reference_spectrum_") && endswith(fn, ".csv") || continue
    ref_path = joinpath(data_dir, fn)
    base = fn[(length("reference_spectrum_")+1):(end-length(".csv"))]
    report_path = joinpath(report_dir, string(base, "_residuals.md"))
    title = @sprintf("Residuals: %s (GI-style)", base)
    reference = GIPaper.load_reference_spectrum(ref_path)
    rows = compare_reference(
        params,
        mq,
        reference;
        solver = solver,
        contact_hyperfine = true,
        use_fine_structure = params.fine_structure.enabled,
        isoscalar_pseudoscalar_annihilation = base == "isoscalar" ? :table_iii : :none,
        strange_mass_GeV = base == "isoscalar" ? mq["s"] : nothing,
    )
    GIPaper.write_residual_report(
        report_path,
        title,
        rows;
        solver = solver,
        contact_hyperfine = true,
        central = params.central,
        contact_momentum_sandwich = params.factors.contact_momentum_sandwich,
        fine_structure_momentum_sandwich = params.factors.fine_structure_momentum_sandwich,
        fine_structure_smeared_kernels = params.factors.fine_structure_smeared_kernels,
        use_fine_structure = params.fine_structure.enabled,
    )
    absres = [abs(r.residual_MeV) for r in rows]
    isempty(absres) && @printf("%s: no rows\n", fn)
    if !isempty(absres)
        mean_abs = sum(absres) / length(absres)
        max_abs = maximum(absres)
        @printf(
            "%s: n=%d mean_abs=%.1f max_abs=%.1f\n",
            fn,
            length(rows),
            mean_abs,
            max_abs
        )
        push!(
            score_rows,
            (
                sector = base,
                n = length(rows),
                mean_abs = mean_abs,
                max_abs = max_abs,
                report = string(base, "_residuals.md"),
            ),
        )
    end
end

open(joinpath(report_dir, "scorecard.md"), "w") do io
    println(io, "# Spectrum Reproduction Scorecard")
    println(io)
    println(io, "Generated by `julia GIPaper/checks/run_all_spectrum_checks.jl`.")
    println(io, numerics_provenance(solver))
    println(
        io,
        "Host generation time: ",
        Dates.format(Dates.now(), dateformat"yyyy-mm-dd\THH:MM"),
    )
    println(io)
    println(io, "| sector | rows | mean abs MeV | max abs MeV | report |")
    println(io, "|---|---:|---:|---:|---|")
    for row in sort(score_rows; by = r -> r.mean_abs)
        println(
            io,
            @sprintf(
                "| `%s` | %d | %.1f | %.1f | [%s](%s) |",
                row.sector,
                row.n,
                row.mean_abs,
                row.max_abs,
                row.report,
                row.report
            )
        )
    end
    println(io)
    println(
        io,
        "Interpretation: heavy-heavy and heavy-light sectors are useful solver diagnostics. The isoscalar sector uses the `:table_iii` scheme: calibrated P1 for the `^1S_0` rows, general Eq. (16) blocks for `^3S_1` (A=+2.5, three gluons) and `^3P_2` (A=-0.8, two gluons), and ideal `n nbar`/`s sbar` mixing for every other channel, as prescribed by Table III. Remaining isoscalar residuals track the corresponding isovector-channel residuals plus one unpaired low-confidence `2^3D_2` digitization.",
    )
end
