#!/usr/bin/env julia

using Printf

root = dirname(@__DIR__)
include(joinpath(root, "src", "GIModel", "GIModel.jl"))
using .GIModel

params = load_parameters(joinpath(root, "data", "parameters.provisional.toml"))
report_path = joinpath(root, "docs", "residual_reports", "heavy_quarkonium_diagnostics.md")
mkpath(dirname(report_path))

const SECTORS = [
    ("charmonium", "c", joinpath(root, "data", "reference_spectrum_charmonium.csv")),
    ("bottomonium", "b", joinpath(root, "data", "reference_spectrum_bottomonium.csv")),
]

function row_label(row)
    @sprintf("%d^%d%s_%d", row.n, row.multiplicity, row.L, row.J)
end

function center_groups(rows)
    groups = Dict{Tuple{Int, String}, Vector{eltype(rows)}}()
    for row in rows
        push!(get!(groups, (row.n, row.L), eltype(rows)[]), row)
    end
    out = Dict{Tuple{Int, String}, NamedTuple}()
    for (key, group) in groups
        weights = [2 * row.J + 1 for row in group]
        wsum = sum(weights)
        ref = sum(w * row.reference_GeV for (w, row) in zip(weights, group)) / wsum
        pred = sum(w * row.predicted_GeV for (w, row) in zip(weights, group)) / wsum
        out[key] = (n = key[1], L = key[2], states = length(group), ref = ref, pred = pred, residual = 1000 * (pred - ref))
    end
    out
end

function split_row(rows, label_a, label_b)
    bylabel = Dict(row_label(row) => row for row in rows)
    haskey(bylabel, label_a) && haskey(bylabel, label_b) || return nothing
    a = bylabel[label_a]
    b = bylabel[label_b]
    ref = 1000 * (a.reference_GeV - b.reference_GeV)
    pred = 1000 * (a.predicted_GeV - b.predicted_GeV)
    (name = "$label_a - $label_b", ref = ref, pred = pred, error = pred - ref)
end

function spacing_row(centers, key_a, key_b)
    haskey(centers, key_a) && haskey(centers, key_b) || return nothing
    a = centers[key_a]
    b = centers[key_b]
    ref = 1000 * (a.ref - b.ref)
    pred = 1000 * (a.pred - b.pred)
    (name = "$(key_a[1])$(key_a[2]) - $(key_b[1])$(key_b[2])", ref = ref, pred = pred, error = pred - ref)
end

"""Share of `sum(r_i^2)` that is removed by subtracting the mean residual (common offset proxy)."""
function fraction_offset_explains(residuals_MeV::Vector{Float64})
    isempty(residuals_MeV) && return 0.0
    sst = sum(abs2, residuals_MeV)
    sst <= 0.0 && return 0.0
    o = sum(residuals_MeV) / length(residuals_MeV)
    sc = sum((r - o)^2 for r in residuals_MeV)
    return 1.0 - sc / sst
end

function spacing_error_from_rows(sp_rows)
    errs = Float64[]
    for row in sp_rows
        isnothing(row) && continue
        push!(errs, row.error)
    end
    isempty(errs) && return (0.0, 0.0, 0)
    n = length(errs)
    rms = sqrt(sum(abs2, errs) / n)
    mae = sum(abs, errs) / n
    return (rms, mae, n)
end

function emit_split_table(io, title, rows)
    valid = [row for row in rows if !isnothing(row)]
    isempty(valid) && return
    println(io, "### ", title)
    println(io)
    println(io, "| quantity | reference MeV | model MeV | error MeV |")
    println(io, "|---|---:|---:|---:|")
    for row in valid
        println(io, @sprintf("| `%s` | %.1f | %.1f | %+7.1f |", row.name, row.ref, row.pred, row.error))
    end
    println(io)
end

open(report_path, "w") do io
    println(io, "# Heavy Quarkonium Diagnostics")
    println(io)
    println(io, "Generated by `julia --project=. scripts/analyze_heavy_quarkonium.jl`.")
    println(io)
    println(io, "Purpose: check whether the active GI central path reproduces `ccbar`/`bbbar`, then separate any remaining mismatch into spin-averaged centers, radial/orbital spacings, and spin splittings.")
    println(io)
    active = central_potential_path(params)
    println(io, "Active central path: `", active.name, "` — ", active.paper_refs)
    println(io)

    for (sector, flavor, path) in SECTORS
        reference = load_reference_spectrum(path)
        rows = compare_sector(
            params, reference, flavor;
            kinetic = :relativistic,
            contact_hyperfine = true,
            use_fine_structure = params.fine_structure,
        )
        residuals = [row.residual_MeV for row in rows]
        offset = sum(residuals) / length(residuals)
        centered_abs = [abs(row.residual_MeV - offset) for row in rows]
        centers = center_groups(rows)

        println(io, "## ", sector)
        println(io)
        println(io, @sprintf("- rows: `%d`", length(rows)))
        println(io, @sprintf("- mean residual/common offset: `%+.1f MeV`", offset))
        println(io, @sprintf("- mean absolute residual: `%.1f MeV`", sum(abs.(residuals)) / length(residuals)))
        println(io, @sprintf("- mean absolute residual after removing common offset: `%.1f MeV`", sum(centered_abs) / length(centered_abs)))
        f_off = fraction_offset_explains(residuals)
        println(
            io,
            @sprintf(
                "- approximate share of *squared* residuals explained by a single common offset: `%.0f%%` (order-of-magnitude; not a full variance decomposition across physics channels)",
                100 * f_off,
            ),
        )
        println(io)

        println(io, "### Multiplet Centers")
        println(io)
        println(io, "| multiplet | states | reference GeV | model GeV | residual MeV | offset-corrected MeV |")
        println(io, "|---|---:|---:|---:|---:|---:|")
        for key in sort(collect(keys(centers)); by = x -> (x[2], x[1]))
            c = centers[key]
            println(
                io,
                @sprintf(
                    "| `%d%s` | %d | %.3f | %.3f | %+7.1f | %+7.1f |",
                    c.n,
                    c.L,
                    c.states,
                    c.ref,
                    c.pred,
                    c.residual,
                    c.residual - offset,
                ),
            )
        end
        println(io)

        sp_rows = [
            spacing_row(centers, (2, "S"), (1, "S")),
            spacing_row(centers, (3, "S"), (1, "S")),
            spacing_row(centers, (1, "P"), (1, "S")),
            spacing_row(centers, (1, "D"), (1, "P")),
            spacing_row(centers, (2, "P"), (1, "P")),
            spacing_row(centers, (2, "D"), (1, "D")),
        ]
        rms_s, mae_s, n_s = spacing_error_from_rows(sp_rows)
        println(io, "- radial/orbital spacing errors (this table): RMSE = `", @sprintf("%.1f", rms_s), " MeV`, mean abs = `", @sprintf("%.1f", mae_s), " MeV` over `", n_s, "` available rows")
        println(io)
        emit_split_table(io, "Radial And Orbital Spacings", sp_rows)

        emit_split_table(
            io,
            "Spin Splittings",
            [
                split_row(rows, "1^3S_1", "1^1S_0"),
                split_row(rows, "2^3S_1", "2^1S_0"),
                split_row(rows, "1^3P_2", "1^3P_1"),
                split_row(rows, "1^3P_1", "1^3P_0"),
                split_row(rows, "2^3P_2", "2^3P_1"),
                split_row(rows, "2^3P_1", "2^3P_0"),
                split_row(rows, "1^3D_3", "1^3D_2"),
                split_row(rows, "1^3D_2", "1^3D_1"),
            ],
        )
    end

    println(io)
    println(io, "## Where to go next (strategy)")
    println(io)
    println(io, "1. Heavy-quarkonium centers and radial/orbital spacings are reproduced at the few-MeV level with the active `appendix_a_momentum_sandwich` central path.")
    println(io, "2. The active contact, tensor, and spin–orbit terms now include GI-style momentum-factor sandwiches; tensor and spin–orbit radial kernels are derived from the smeared Appendix-A `G̃(r)`/`S̃(r)` derivatives.")
    println(io, "3. The next equal-mass refinement is to audit remaining extraction/rounding ambiguity in the plotted charmonium labels and compare the perturbative FD treatment against the paper's HO-basis implementation order.")
    println(io, "4. Heavy–light and light sectors still require unequal-mass antisymmetric spin–orbit mixing, same-J tensor mixing, annihilation/mixing, and eventually coupled-channel physics; do not read their residuals as a failure of the heavy-heavy GI reproduction.")
    println(io, "5. Close the extraction loop: log text-vs-figure issues in `data/raw/extraction_audit.csv` and promote reference rows to `data/clean/` with provenance before arguing about sub-5-MeV agreement.")
    println(io)
end

println("wrote $report_path")
