#!/usr/bin/env python3
"""Audit explicit @ref links in core API docstrings (not Julia call dependencies).

Run from any directory: python3 scripts/audit_doc_links.py
Use --baseline REF to compare against a different Git revision (default HEAD).
"""
import argparse
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
CORE = '''load_parameters load_quark_masses load_parameters_and_quark_masses
GIParameters QuarkMassTable ConstituentMasses Meson reduced_mass flavor_label
is_equal_flavor BasisState spectrum_levels
compute_spectrum MixedSpectrum MixedState StateMixing spectrum_state
radial_wave physical_components RadialWave sample_wave wave_norm
physical_state_amplitude compute_isoscalar_spectrum'''.split()
DOC = re.compile(r'"""(.*?)"""', re.S)
DECL = re.compile(r'\s*(?:#[^\n]*\n\s*)*(?:(?:mutable\s+)?struct\s+|abstract\s+type\s+|function\s+|const\s+)?([A-Za-z_]\w*)')
LINK = re.compile(r'\[`([^`]+)`\]\(@ref\)')


def collect(revision=None):
    docs = {}
    for path in sorted((ROOT / 'src').glob('*.jl')):
        text = (subprocess.check_output(['git', 'show', f'{revision}:{path.relative_to(ROOT)}'], cwd=ROOT, text=True)
                if revision else path.read_text())
        for match in DOC.finditer(text):
            declaration = DECL.match(text, match.end())
            if declaration:
                docs.setdefault(declaration[1], []).append(match[1])
    return {name: set(LINK.findall('\n'.join(bodies))) - {name} for name, bodies in docs.items()}


def metrics(graph):
    edges = {(a, b) for a in CORE for b in graph.get(a, set()) if b in CORE}
    incoming = {n: sum(b == n for a, b in edges) for n in CORE}
    outgoing = {n: sum(a == n for a, b in edges) for n in CORE}
    return edges, incoming, outgoing


def reachable(graph, start):
    seen, todo = {start}, [start]
    while todo:
        for target in graph.get(todo.pop(), set()) & set(CORE) - seen:
            seen.add(target)
            todo.append(target)
    return seen


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--baseline', default='HEAD')
    args = parser.parse_args()
    revision = subprocess.check_output(
        ['git', 'rev-parse', args.baseline], cwd=ROOT, text=True).strip()
    before, after = collect(revision), collect()
    be, bi, bo = metrics(before)
    ae, ai, ao = metrics(after)
    lines = ['# Public API documentation link audit', '',
             'See [Discoverability](discoverability.md) for the documentation conventions.', '',
             'Generated by `python3 scripts/audit_doc_links.py`. Nodes are a curated set of',
             f'{len(CORE)} public entry points along the input → spectrum → wavefunction workflow.',
             'Edges are explicit ``[`name`](@ref)`` links in source docstrings, directed from',
             'the entry being read to its linked destination. Overloads are merged; self-links',
             'are excluded. This is a static documentation graph, not a call graph or a',
             'measurement of Pluto rendering. Prose and code identifiers without links do not count.', '',
             f'Baseline: `{revision}`. Core edges: **{len(be)} → {len(ae)}**.',
             f'Entries with no incoming core link: **{sum(v == 0 for v in bi.values())} → {sum(v == 0 for v in ai.values())}**.',
             f'Entries with no outgoing core link: **{sum(v == 0 for v in bo.values())} → {sum(v == 0 for v in ao.values())}**.',
             f'Core entries reachable from `Meson` (including itself): **{len(reachable(before, "Meson"))} → {len(reachable(after, "Meson"))} of {len(CORE)}**.', '',
             '| Entry | Incoming before → after | Outgoing before → after |',
             '|---|---:|---:|']
    lines += [f'| `{n}` | {bi[n]} → {ai[n]} | {bo[n]} → {ao[n]} |' for n in CORE]
    route = [
        ('QuarkMassTable', 'load_quark_masses'),
        ('load_quark_masses', 'load_parameters_and_quark_masses'),
        ('load_parameters', 'load_parameters_and_quark_masses'),
        ('load_parameters_and_quark_masses', 'Meson'),
        ('ConstituentMasses', 'Meson'), ('Meson', 'reduced_mass'),
        ('Meson', 'flavor_label'), ('Meson', 'is_equal_flavor'),
        ('Meson', 'spectrum_levels'),
        ('spectrum_levels', 'BasisState'), ('Meson', 'compute_spectrum'),
        ('compute_spectrum', 'MixedSpectrum'), ('MixedSpectrum', 'MixedState'),
        ('MixedSpectrum', 'spectrum_state'), ('spectrum_state', 'physical_components'),
        ('MixedState', 'StateMixing'), ('physical_components', 'RadialWave'),
        ('physical_components', 'physical_state_amplitude'),
        ('spectrum_state', 'radial_wave'), ('radial_wave', 'sample_wave'),
        ('radial_wave', 'wave_norm'),
        ('BasisState', 'compute_isoscalar_spectrum'),
    ]
    lines += ['', '## Suggested reading paths', '',
              'A selected subset of actual links makes the main workflow easier to read.',
              '', '```mermaid', 'flowchart LR']
    lines += [f'    {a} --> {b}' for a, b in route if (a, b) in ae]
    lines += ['```', '', '## Complete graph after editing', '',
              '<details>', '<summary>Show all core documentation links</summary>', '',
              '```mermaid', 'flowchart LR']
    lines += [f'    {n}["{n}"]' for n in CORE]
    lines += [f'    {a} --> {b}' for a, b in sorted(ae)]
    lines += ['```', '', '</details>', '',
              'This curated sample covers the main workflow. Extend `CORE` to audit',
              'additional observables or solver methods. For how to interpret the links,',
              'see [Discoverability](discoverability.md).', '']
    output = ROOT / 'docs' / 'discoverability_graph.md'
    output.write_text('\n'.join(lines))
    print(f'{output}: {len(be)} -> {len(ae)} core links')

if __name__ == '__main__':
    main()
