#!/usr/bin/env julia
# Diagnose the missing GI pseudoscalar isoscalar annihilation/chiral block.

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Printf

root = dirname(@__DIR__)
using GIModel

params_path = joinpath(root, "data", "parameters.provisional.toml")
params, mq = load_parameters_and_quark_masses(params_path)

data_dir = joinpath(root, "data")
report_dir = joinpath(root, "docs", "residual_reports")
mkpath(report_dir)

function pseudoscalar_refs(reference)
    rows = [
        row for row in reference if
        row.L == "S" && row.multiplicity == 1 && row.J == 0 && row.n in (1, 2)
    ]
    groups = Dict{Int,Vector{ReferenceState}}()
    for row in rows
        push!(get!(groups, row.n, ReferenceState[]), row)
    end
    return groups
end

function branch_predictions(params, reference, mass)
    masses = ConstituentMasses(mass, mass)
    annotated = [ReferenceStateWithMasses(row, masses) for row in reference]
    computed = compute_sector(params, annotated; kinetic = :relativistic)
    rows = compare(
        computed,
        annotated;
        contact_hyperfine = true,
        use_fine_structure = params.fine_structure,
    )
    return Dict((row.n, row.multiplicity, row.L, row.J) => row.predicted_GeV for row in rows)
end

isoscalar_ref = load_reference_spectrum(joinpath(data_dir, "reference_spectrum_isoscalar.csv"))
groups = pseudoscalar_refs(isoscalar_ref)

nn_pred = branch_predictions(params, isoscalar_ref, mq["q"])
ss_pred = branch_predictions(params, isoscalar_ref, mq["s"])

labels = ["1 n nbar", "1 s sbar", "2 n nbar", "2 s sbar"]
diagonal = [
    nn_pred[(1, 1, "S", 0)],
    ss_pred[(1, 1, "S", 0)],
    nn_pred[(2, 1, "S", 0)],
    ss_pred[(2, 1, "S", 0)],
]

target = Float64[]
for n in (1, 2)
    refs = sort(groups[n]; by = row -> row.mass_GeV)
    append!(target, [refs[1].mass_GeV, refs[end].mass_GeV])
end
target = sort(target)

solution = isoscalar_pseudoscalar_annihilation_solution(diagonal; targets = target)
labels = [state.label for state in solution.block.basis]

open(joinpath(report_dir, "pseudoscalar_annihilation_audit.md"), "w") do io
    println(io, "# Pseudoscalar Annihilation Audit")
    println(io)
    println(io, "Generated by `julia scripts/audit_pseudoscalar_annihilation.jl`.")
    println(io)
    println(io, "## Paper Clues")
    println(io)
    println(
        io,
        "- GI treats annihilation only after the fixed-`L,S,J` diagonalization and only for self-conjugate isoscalars.",
    )
    println(
        io,
        "- Most isoscalar channels can be described by one annihilation parameter, but the pseudoscalar `^1S_0` channel is singled out as exceptional because of U(1)/chiral nonperturbative physics.",
    )
    println(
        io,
        "- Table III uses `A(P1)=+0.5`; for `P2` it uses `A=+0.55` and `M0=1.17 GeV`, with mass-dependent, non-orthogonal poles.",
    )
    println(
        io,
        "- The text describes the Cohen-Lipkin-Isgur mechanism: a positive annihilation amplitude shifts wavefunction-at-origin strength into higher pseudoscalar states.",
    )
    println(io)
    println(io, "## Rank-One Reconstruction")
    println(io)
    println(
        io,
        "As a local debug test, build the unmixed basis `[1 n nbar, 1 s sbar, 2 n nbar, 2 s sbar]` from the current model and ask whether a positive rank-one annihilation update can reproduce the four digitized GI isoscalar pseudoscalar masses.",
    )
    println(io)
    println(io, "| basis | unmixed GeV | coupling sqrt(GeV) | weight GeV |")
    println(io, "|---|---:|---:|---:|")
    for i in eachindex(labels)
        println(
            io,
            @sprintf(
                "| `%s` | %.3f | %.3f | %.3f |",
                labels[i],
                solution.diagonal_GeV[i],
                solution.couplings_sqrt_GeV[i],
                solution.weights_GeV[i],
            ),
        )
    end
    println(io)
    println(io, "All weights are positive, so the target spectrum has the interlacing expected from adding one positive annihilation channel.")
    println(io)
    println(io, "## Reconstructed Spectrum")
    println(io)
    println(io, "| state | target GeV | reconstructed GeV | residual MeV | components `(1n,1s,2n,2s)` |")
    println(io, "|---|---:|---:|---:|---|")
    for i in eachindex(target)
        comp = join([@sprintf("%+.2f", solution.vectors[j, i]) for j in 1:length(labels)], ", ")
        println(
            io,
            @sprintf(
                "| `%d` | %.3f | %.3f | %+6.1f | `%s` |",
                i,
                target[i],
                solution.masses[i],
                1000 * (solution.masses[i] - target[i]),
                comp,
            ),
        )
    end
    println(io)
    println(io, "## Annihilation Matrix")
    println(io)
    println(io, "Entries are in MeV in the same basis order.")
    println(io)
    println(io, "| | 1n | 1s | 2n | 2s |")
    println(io, "|---|---:|---:|---:|---:|")
    for i in eachindex(labels)
        vals = [
            @sprintf("%.1f", 1000 * solution.annihilation_matrix_GeV[i, j])
            for j in eachindex(labels)
        ]
        println(io, "| `$(labels[i])` | ", join(vals, " | "), " |")
    end
    println(io)
    println(io, "## Debug Read")
    println(io)
    println(
        io,
        "The current model's unmixed pseudoscalar masses are not globally wrong: a single positive radial/flavor annihilation channel maps them onto the GI isoscalar pseudoscalar masses exactly in this four-state diagnostic.",
    )
    println(
        io,
        "The inferred eigenvectors are qualitatively Table-III/P1-like for the first two states, including a near octet/singlet `eta`/`eta'` pattern and non-negligible radial components. The implemented `:calibrated_p1` comparison path therefore addresses the local pseudoscalar failure without another contact hyperfine retune; the full mass-dependent P2 prescription remains open.",
    )
end

println("wrote ", joinpath(report_dir, "pseudoscalar_annihilation_audit.md"))
