#!/usr/bin/env julia
# Build diagnostics that separate non-mixing score quality from S-wave contact
# hyperfine stress.

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Dates
using Printf

root = dirname(@__DIR__)
using GIModel

params_path = joinpath(root, "data", "parameters.provisional.toml")
params, mq = load_parameters_and_quark_masses(params_path)
params_ho = GIModel.with_basis(params, HarmonicOscillatorBasis)

function with_contact_momentum_sandwich(params::GIParameters{Basis}, enabled::Bool) where {Basis}
    return GIParameters{Basis}(
        params.b,
        params.c,
        params.sigma0,
        params.smearing_s,
        params.appendix_a_smearing,
        params.appendix_a_derivative_g,
        params.appendix_a_closed_form,
        params.appendix_a_momentum_sandwich,
        enabled,
        params.epsilon_c,
        params.epsilon_t,
        params.epsilon_so_vector,
        params.epsilon_so_scalar,
        params.fine_structure_momentum_sandwich,
        params.fine_structure_smeared_kernels,
        params.fine_structure,
        params.k_spin_orbit,
        params.k_tensor,
        params.coulomb_1d_smear,
    )
end

const FLAVOR = Dict(
    "reference_spectrum_charmonium.csv" => "c",
    "reference_spectrum_bottomonium.csv" => "b",
    "reference_spectrum_charmed.csv" => "c",
    "reference_spectrum_b_flavored.csv" => "b",
    "reference_spectrum_strange.csv" => "q",
    "reference_spectrum_isovector.csv" => "q",
    "reference_spectrum_isoscalar.csv" => "q",
)

data_dir = joinpath(root, "data")
report_dir = joinpath(root, "docs", "residual_reports")
mkpath(report_dir)

params_diagonal_contact = with_contact_momentum_sandwich(params, false)
all_rows = NamedTuple[]
all_rows_ho = NamedTuple[]
contact_rows = NamedTuple[]

for fn in sort(readdir(data_dir))
    startswith(fn, "reference_spectrum_") && endswith(fn, ".csv") || continue
    base = fn[(length("reference_spectrum_")+1):(end-length(".csv"))]
    flavor = get(FLAVOR, fn, "q")
    reference = load_reference_spectrum(joinpath(data_dir, fn))
    annotated = attach_constituent_masses(mq, reference, mq[flavor])
    computed = compute_sector(params, annotated; kinetic = :relativistic)
    rows = compare(computed, annotated; contact_hyperfine = true, use_fine_structure = params.fine_structure)
    append!(all_rows, rows)

    computed_ho = compute_sector(params_ho, annotated; kinetic = :relativistic)
    rows_ho = compare(
        computed_ho,
        annotated;
        contact_hyperfine = true,
        use_fine_structure = params_ho.fine_structure,
    )
    append!(all_rows_ho, rows_ho)

    diagonal_computed = SectorComputation(params_diagonal_contact, computed.channel_cache)
    diagonal_rows = compare(
        diagonal_computed,
        annotated;
        contact_hyperfine = true,
        use_fine_structure = params.fine_structure,
    )

    for (active, diagonal) in zip(rows, diagonal_rows)
        active.L == "S" || continue
        active.multiplicity in (1, 3) || continue
        push!(
            contact_rows,
            (
                sector = active.sector,
                state = @sprintf("%d^%d%s_%d", active.n, active.multiplicity, active.L, active.J),
                reference_GeV = active.reference_GeV,
                active_contact_MeV = 1000 * active.contact_shift_GeV,
                diagonal_contact_MeV = 1000 * diagonal.contact_shift_GeV,
                residual_MeV = active.residual_MeV,
                mixing_prone = mixing_prone_state(active),
            ),
        )
    end
end

summary = nonmixing_deviation_summary(all_rows)
summary_ho = nonmixing_deviation_summary(all_rows_ho)

open(joinpath(report_dir, "nonmixing_scorecard.md"), "w") do io
    println(io, "# Non-Mixing Residual Scorecard")
    println(io)
    println(io, "Generated by `julia scripts/audit_nonmixing_contact.jl`.")
    println(io, "Host generation time: ", Dates.format(Dates.now(), dateformat"yyyy-mm-dd\THH:MM"))
    println(io)
    println(
        io,
        "Rows marked as likely to require explicit mixing are excluded: isoscalar flavor mixing, open-flavor same-`J` `^1L_J`/`^3L_J` candidates, and triplet `S`/`D`, `J=1` tensor/radial candidates.",
    )
    println(io)
    println(io, "| sector | included | excluded | mean abs deviation MeV | max abs deviation MeV |")
    println(io, "|---|---:|---:|---:|---:|")
    for row in sort(summary; by = r -> (isnan(r.mean_abs_deviation_MeV), r.mean_abs_deviation_MeV))
        mean_s = isnan(row.mean_abs_deviation_MeV) ? "n/a" : @sprintf("%.1f", row.mean_abs_deviation_MeV)
        max_s = isnan(row.max_abs_deviation_MeV) ? "n/a" : @sprintf("%.1f", row.max_abs_deviation_MeV)
        println(
            io,
            @sprintf(
                "| `%s` | %d | %d | %s | %s |",
                row.sector,
                row.n_included,
                row.n_excluded_mixing_prone,
                mean_s,
                max_s,
            ),
        )
    end
end

function row_key(row)
    return (row.sector, row.state, row.L, row.n, row.J, row.multiplicity, row.reference_GeV)
end

fd_by_key = Dict(row_key(row) => row for row in all_rows if !mixing_prone_state(row))
ho_by_key = Dict(row_key(row) => row for row in all_rows_ho if !mixing_prone_state(row))
common_keys = sort(collect(intersect(keys(fd_by_key), keys(ho_by_key))); by = x -> (x[1], x[4], x[3], x[6], x[5], x[2]))
summary_ho_by_sector = Dict(row.sector => row for row in summary_ho)

open(joinpath(report_dir, "basis_nonmixing_comparison.md"), "w") do io
    println(io, "# Non-Mixing Basis Comparison")
    println(io)
    println(io, "Generated by `julia scripts/audit_nonmixing_contact.jl`.")
    println(io, "FD = current `FiniteDifferenceBasis`; HO = first finite `HarmonicOscillatorBasis` audit path.")
    println(io)
    println(
        io,
        "HO caveat: the spin-independent Hamiltonian is assembled in the oscillator subspace with a per-channel variational beta scan; spin-dependent expectations are evaluated on reconstructed mesh wavefunctions.",
    )
    println(io)
    println(io, "## Sector Summary")
    println(io)
    println(io, "| sector | rows | excluded | FD mean abs | FD max abs | HO mean abs | HO max abs |")
    println(io, "|---|---:|---:|---:|---:|---:|---:|")
    for fd in sort(summary; by = r -> (isnan(r.mean_abs_deviation_MeV), r.mean_abs_deviation_MeV))
        ho = get(summary_ho_by_sector, fd.sector, nothing)
        ho_mean = isnothing(ho) || isnan(ho.mean_abs_deviation_MeV) ? "n/a" : @sprintf("%.1f", ho.mean_abs_deviation_MeV)
        ho_max = isnothing(ho) || isnan(ho.max_abs_deviation_MeV) ? "n/a" : @sprintf("%.1f", ho.max_abs_deviation_MeV)
        fd_mean = isnan(fd.mean_abs_deviation_MeV) ? "n/a" : @sprintf("%.1f", fd.mean_abs_deviation_MeV)
        fd_max = isnan(fd.max_abs_deviation_MeV) ? "n/a" : @sprintf("%.1f", fd.max_abs_deviation_MeV)
        println(
            io,
            @sprintf(
                "| `%s` | %d | %d | %s | %s | %s | %s |",
                fd.sector,
                fd.n_included,
                fd.n_excluded_mixing_prone,
                fd_mean,
                fd_max,
                ho_mean,
                ho_max,
            ),
        )
    end
    println(io)
    println(io, "## State Table")
    println(io)
    println(io, "| sector | state | ref | FD pred | HO pred | FD resid | HO resid | HO-FD |")
    println(io, "|---|---|---:|---:|---:|---:|---:|---:|")
    for key in common_keys
        fd = fd_by_key[key]
        ho = ho_by_key[key]
        label = @sprintf("%d^%d%s_%d", fd.n, fd.multiplicity, fd.L, fd.J)
        println(
            io,
            @sprintf(
                "| `%s` | `%s` | %.3f | %.3f | %.3f | %+7.1f | %+7.1f | %+7.1f |",
                fd.sector,
                label,
                fd.reference_GeV,
                fd.predicted_GeV,
                ho.predicted_GeV,
                fd.residual_MeV,
                ho.residual_MeV,
                1000 * (ho.predicted_GeV - fd.predicted_GeV),
            ),
        )
    end
end

open(joinpath(report_dir, "contact_hyperfine_audit.md"), "w") do io
    println(io, "# Contact Hyperfine Audit")
    println(io)
    println(io, "Generated by `julia scripts/audit_nonmixing_contact.jl`.")
    println(io)
    println(io, "## Paper Clues")
    println(io)
    println(
        io,
        "- Appendix A says the contact, tensor, vector spin-orbit, and scalar spin-orbit potentials are modified by momentum-dependent `m/E` factors, replacing naive light-quark mass denominators by energy denominators when `epsilon_i = 0`.",
    )
    println(
        io,
        "- This requires a side exponent `1/2 + epsilon_i` in the Hermitian sandwich. A smaller side exponent only partially replaces `1/(m1 m2)` by `1/(E1 E2)` and leaves light-quark contact terms too large.",
    )
    println(
        io,
        "- The smearing width in (A9) is flavor dependent and was designed so light-quark systems do not inherit an unchecked `1/(m1 m2)` contact singularity.",
    )
    println(
        io,
        "- GI evaluated the nonlocal `f(p) V(r) f(p)` operators in a large harmonic-oscillator basis; this repo currently evaluates the same idea on the finite-difference `p^2` eigenbasis, now selected through `GIParameters{Basis}` dispatch.",
    )
    println(
        io,
        "- The first GI diagonalization is already in fixed `L,S,J` sectors, so the contact term is part of the S-wave radial problem rather than only a first-order correction on a spin-independent wavefunction. This matters most in the pion/kaon-sized light pseudoscalar splittings.",
    )
    println(io)
    println(io, "## Sector-Level Contact Stress")
    println(io)
    println(io, "| sector | S rows | mean abs active contact MeV | max abs active contact MeV | mean active/diagonal magnitude | mean abs residual MeV |")
    println(io, "|---|---:|---:|---:|---:|---:|")
    for sector in sort(unique(row.sector for row in contact_rows))
        rows = [row for row in contact_rows if row.sector == sector && !row.mixing_prone]
        isempty(rows) && continue
        active_abs = abs.([row.active_contact_MeV for row in rows])
        residual_abs = abs.([row.residual_MeV for row in rows])
        ratios = [
            abs(row.diagonal_contact_MeV) > 0 ? abs(row.active_contact_MeV / row.diagonal_contact_MeV) : NaN
            for row in rows
        ]
        ratios = [x for x in ratios if isfinite(x)]
        println(
            io,
            @sprintf(
                "| `%s` | %d | %.1f | %.1f | %.3f | %.1f |",
                sector,
                length(rows),
                sum(active_abs) / length(active_abs),
                maximum(active_abs),
                sum(ratios) / length(ratios),
                sum(residual_abs) / length(residual_abs),
            ),
        )
    end
    println(io)
    println(io, "## Largest Non-Mixed S-Wave Residuals")
    println(io)
    println(io, "| sector | state | residual MeV | active contact MeV | diagonal contact MeV |")
    println(io, "|---|---|---:|---:|---:|")
    kept = [row for row in contact_rows if !row.mixing_prone]
    for row in sort(kept; by = r -> -abs(r.residual_MeV))[1:min(16, length(kept))]
        println(
            io,
            @sprintf(
                "| `%s` | `%s` | %+7.1f | %+7.1f | %+7.1f |",
                row.sector,
                row.state,
                row.residual_MeV,
                row.active_contact_MeV,
                row.diagonal_contact_MeV,
            ),
        )
    end
    println(io)
    println(io, "## Audit Read")
    println(io)
    println(
        io,
        "The non-mixing scorecard is the central guardrail: if spin-averaged, non-mixed centers are good while S-wave rows remain split in opposite directions, the mismatch is localized to contact hyperfine strength/order rather than to the central potential.",
    )
    println(
        io,
        "After enforcing the Appendix-A side exponent and diagonalizing the finite-difference S-wave contact operator nonperturbatively, the light pseudoscalar ground-state mismatch changes from the dominant failure to a bounded residual (`isovector 1^1S_0` and `strange 1^1S_0` are now tens, not hundreds, of MeV). The remaining edge is consistent with the paper's warning that pseudoscalar channels are unusually sensitive to relativistic smearing and annihilation/chiral dynamics.",
    )
end

println("wrote ", joinpath(report_dir, "nonmixing_scorecard.md"))
println("wrote ", joinpath(report_dir, "contact_hyperfine_audit.md"))
println("wrote ", joinpath(report_dir, "basis_nonmixing_comparison.md"))
