#!/usr/bin/env python3
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RAW_TEXT = ROOT / "paper" / "text" / "pdftotext_raw.txt"
OUTPUT = ROOT / "paper" / "text" / "godfrey_isgur_1985_readable.md"


HEADER = """# Godfrey-Isgur 1985 Readable Working Markdown

Derived from `paper/text/pdftotext_raw.txt`, generated by `pdftotext -raw`
from `paper/Godfrey-Isgur-1985.pdf`.

This file is optimized for reading and search. It applies conservative OCR
cleanup, removes obvious page headers/footers, dehyphenates prose, and joins
paragraph lines. It is not an authority for equations, signs, symbols, state
labels, or numerical tables.

For numerical extraction, verify against:

- `paper/Godfrey-Isgur-1985.pdf`
- `paper/text/pdftotext_layout.txt`
- `paper/text/pdftotext_bbox.html`
- rendered page images in `paper/pages/`

"""


REPLACEMENTS = {
    "\x02": "",
    "Uniuersity": "University",
    "hive revolutionized": "have revolutionized",
    "urilikely": "unlikely",
    "HAMII. TONIAN": "HAMILTONIAN",
    "HAMII.TONIAN": "HAMILTONIAN",
    "GQDFREY": "GODFREY",
    "FICx.": "FIG.",
    "FICs.": "FIG.",
    "FICi.": "FIG.",
    "FIGr.": "FIG.",
    "GreV": "GeV",
    "Grev": "GeV",
    "Ge V": "GeV",
    "Me V": "MeV",
    "Mev": "MeV",
    "We .substantiate": "We substantiate",
    "pion to the upsilon \"an": "pion to the upsilon can",
    "nonperturbatiUe": "nonperturbative",
    "@CD": "QCD",
    "FinaHy": "Finally",
    "potent1als": "potentials",
    "%'hile": "While",
    "%'e": "We",
    "%'idth": "Width",
    "%'idths": "Widths",
    "Schrodinger": "Schrodinger",
    "Ph. D.": "Ph.D.",
    "Ph. D": "Ph.D.",
}


SECTION_RE = re.compile(
    r"^(?:[IVX]+\.\s+[A-Z]|APPENDIX\s+[A-Z]:|TABLE\s+[IVX]+\.|FIG\.\s*\d+)"
)
HEADER_RE = re.compile(
    r"^(?:\d+\s+STEPHEN GODFREY AND NATHAN ISGUR\s+\d+|"
    r"\d+\s+MESONS IN A RELATIVISTIC QUARK MODEL.*|"
    r"PHYSICAL REVIEW D VOLUME 32, NUMBER 1 1 JULY 1985|"
    r"\d{2,3}\s*$|32\s*$)"
)


def clean_line(line: str) -> str:
    line = line.strip()
    for old, new in REPLACEMENTS.items():
        line = line.replace(old, new)
    line = re.sub(r"\s+", " ", line)
    line = re.sub(r"\bFIG\.\s*([0-9]+)", r"FIG. \1", line)
    return line.strip()


def is_header_or_footer(line: str) -> bool:
    return bool(HEADER_RE.match(line))


def is_section(line: str) -> bool:
    return bool(SECTION_RE.match(line))


def is_equationish(line: str) -> bool:
    if is_section(line):
        return False
    math_chars = sum(line.count(ch) for ch in "=+-—*/()[]{}_^~<>")
    digit_chars = sum(ch.isdigit() for ch in line)
    alpha_chars = sum(ch.isalpha() for ch in line)
    if len(line) < 75 and math_chars >= 3:
        return True
    if digit_chars >= 4 and alpha_chars <= 12:
        return True
    return False


def append_paragraph(out: list[str], paragraph: list[str]) -> None:
    if not paragraph:
        return

    text = ""
    for line in paragraph:
        if not text:
            text = line
            continue
        if text.endswith("-") and line[:1].islower():
            text = text[:-1] + line
        else:
            text += " " + line

    out.append(text.strip())
    paragraph.clear()


def readable_page(page: str) -> str:
    out: list[str] = []
    paragraph: list[str] = []

    for raw_line in page.splitlines():
        line = clean_line(raw_line)
        if not line or is_header_or_footer(line):
            append_paragraph(out, paragraph)
            continue

        if is_section(line):
            append_paragraph(out, paragraph)
            out.append(f"### {line}")
            continue

        if is_equationish(line):
            append_paragraph(out, paragraph)
            out.append(f"`{line}`")
            continue

        paragraph.append(line)

    append_paragraph(out, paragraph)
    return "\n\n".join(out).strip()


def main() -> int:
    if not RAW_TEXT.exists():
        raise SystemExit(f"missing raw text: {RAW_TEXT}")

    pages = RAW_TEXT.read_text(errors="replace").split("\f")
    chunks = [HEADER]

    for index, page in enumerate(pages, start=1):
        body = readable_page(page)
        if not body:
            continue
        chunks.append(f"## PDF Page {index}\n\n{body}\n\n")

    OUTPUT.write_text("".join(chunks))
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

