#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LAYOUT_TEXT = ROOT / "paper" / "text" / "pdftotext_layout.txt"
OUTPUT = ROOT / "paper" / "text" / "godfrey_isgur_1985.md"


HEADER = """# Godfrey-Isgur 1985 Working Markdown

Derived from `paper/text/pdftotext_layout.txt`, generated by `pdftotext -layout`
from `paper/Godfrey-Isgur-1985.pdf`.

This file is a search and navigation aid only. The PDF and page images remain
the authority for equations, signs, symbols, state labels, and numerical tables.

"""


def main() -> int:
    if not LAYOUT_TEXT.exists():
        raise SystemExit(f"missing layout text: {LAYOUT_TEXT}")

    pages = LAYOUT_TEXT.read_text(errors="replace").split("\f")
    chunks = [HEADER]

    for number, page in enumerate(pages, start=1):
        body = page.strip("\n")
        if not body.strip():
            continue

        chunks.append(f"## PDF Page {number}\n\n")
        chunks.append("```text\n")
        chunks.append(body.rstrip())
        chunks.append("\n```\n\n")

    OUTPUT.write_text("".join(chunks))
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

