#!/usr/bin/env julia
# Pointwise V(r) vs experimental (A7)–(A8) 3D-smoothed G+S on the same FD mesh
# (not (A12)–(A13)). Writes `docs/residual_reports/appendix_a_bracket_ccbar.md`.
using Printf

root = dirname(@__DIR__)
include(joinpath(root, "src", "GIModel", "GIModel.jl"))
using .GIModel

tbase = joinpath(root, "data", "parameters.provisional.toml")
mktempdir() do d
    pfalse = joinpath(d, "off.toml")
    ptrue = joinpath(d, "on.toml")
    s = read(tbase, String)
    @assert occursin("appendix_a_smearing = false", s)
    write(pfalse, s)
    write(ptrue, replace(s, "appendix_a_smearing = false" => "appendix_a_smearing = true"))
    params0 = load_parameters(pfalse)
    params1 = load_parameters(ptrue)
    m1 = m2 = params0.masses["c"]
    ngrid = 300
    rmax = 20.0
    r, _h = GIModel.radial_grid(ngrid, rmax)
    v0 = GIModel.potential_diagonal(params0, m1, m2, r)
    v1 = GIModel.potential_diagonal(params1, m1, m2, r)
    δ = v1 .- v0
    n = length(δ)
    l2 = sqrt(sum(abs2, δ) / n)
    l1 = sum(abs, δ) / n
    linf = maximum(abs, δ)
    r_at_max = r[argmax(abs.(δ))]

    out = joinpath(root, "docs", "residual_reports", "appendix_a_bracket_ccbar.md")
    mkpath(dirname(out))
    open(out, "w") do io
        println(io, "# Appendix A bracket: pointwise central vs (A7)–(A8) 3D smearing")
        println(io)
        println(
            io,
            "Auto-generated by `julia --project=. scripts/compare_central_pointwise_vs_a7a8.jl`.\n",
        )
        println(io, "This compares **the same** Table II + mesh: only `appendix_a_smearing` toggles")
        println(io, "`potential_diagonal` between pointwise *V* and the experimental 3D blur in")
        println(io, "`smeared_central_values` (not the paper’s (A12)–(A13) derivative expansion).")
        println(io)
        println(io, "- Equal-mass **ccbar**, `radial_grid(ngrid=$ngrid, rmax=$rmax)`")
        println(io, @sprintf("- Mesh L2 mean diff `||V_\\mathrm{smear}-V_\\mathrm{pt}||_2/\\sqrt{n}` ≈ `%.3f` GeV", l2))
        println(io, @sprintf("- Mesh mean |diff| ≈ `%.3f` GeV; max |diff| ≈ `%.3f` GeV near `r ≈ %.2f` GeV⁻¹", l1, linf, r_at_max))
        println(io)
        cp0 = GIModel.central_potential_path(params0)
        cp1 = GIModel.central_potential_path(params1)
        println(io, "Active path (off): `", cp0.name, "` — ", cp0.notes)
        println(io, "Active path (on):  `", cp1.name, "` — ", cp1.notes)
        println(io)
        println(io, "| r [GeV⁻¹] | V_point [GeV] | V_A7A8blur [GeV] | diff |")
        println(io, "|---:|---:|---:|---:|")
        for i in (1, div(n, 4), div(n, 2), 3 * div(n, 4), n)
            println(io, @sprintf("| %.2f | %.4f | %.4f | %.4f |", r[i], v0[i], v1[i], δ[i]))
        end
        println("wrote $out")
    end
end
