#!/usr/bin/env julia
# Compare the available spin-independent central potential paths on one FD mesh.
using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Printf

root = dirname(@__DIR__)
using GIModel

params = load_parameters(joinpath(root, "data", "parameters.provisional.toml"))
m1 = m2 = params.masses["c"]
ngrid = 300
rmax = 20.0
r, _h = GIModel.radial_grid(ngrid, rmax)

paths = [
    (:pointwise, "pointwise V"),
    (:appendix_a_closed_form, "closed-form GI G~+S~"),
    (
        :appendix_a_momentum_sandwich,
        "diagonal view of GI G~+S~ (matrix sandwich in Hamiltonian)",
    ),
    (:appendix_a_3d_a7a8, "3D A7-A8 blur of G+S"),
    (:coulomb_1d, "1D Gaussian G only"),
    (:appendix_a_derivative_g, "derivative proxy G + lap(G)/(4sigma^2)"),
]

values = Dict(
    mode => GIModel.central_potential_values(params, m1, m2, r; mode = mode) for
    (mode, _label) in paths
)
base = values[:pointwise]

out = joinpath(root, "docs", "residual_reports", "central_potential_paths_ccbar.md")
mkpath(dirname(out))
open(out, "w") do io
    println(io, "# Central-potential path comparison: ccbar")
    println(io)
    println(io, "Auto-generated by `julia scripts/compare_central_paths.jl`.")
    println(io)
    println(
        io,
        "All rows use the same Table II parameters and `radial_grid(ngrid=$ngrid, rmax=$rmax)`.",
    )
    println(
        io,
        "The derivative path is a finite-difference Appendix-A proxy, not a completed audited (A12)-(A13) transcription.",
    )
    println(io)
    println(
        io,
        "| mode | description | mean abs diff GeV | rms diff GeV | max abs diff GeV | r at max GeV^-1 |",
    )
    println(io, "|---|---|---:|---:|---:|---:|")
    for (mode, label) in paths
        δ = values[mode] .- base
        mean_abs = sum(abs, δ) / length(δ)
        rms = sqrt(sum(abs2, δ) / length(δ))
        max_abs = maximum(abs.(δ))
        r_at_max = r[argmax(abs.(δ))]
        println(
            io,
            @sprintf(
                "| `%s` | %s | %.5f | %.5f | %.5f | %.3f |",
                String(mode),
                label,
                mean_abs,
                rms,
                max_abs,
                r_at_max,
            ),
        )
    end
    println(io)
    println(io, "## Samples")
    println(io)
    println(io, "| r GeV^-1 | pointwise | closed-form | A7-A8 3D | 1D G | derivative G |")
    println(io, "|---:|---:|---:|---:|---:|---:|")
    for i in (1, div(ngrid, 10), div(ngrid, 4), div(ngrid, 2), 3 * div(ngrid, 4), ngrid)
        println(
            io,
            @sprintf(
                "| %.3f | %.5f | %.5f | %.5f | %.5f | %.5f |",
                r[i],
                values[:pointwise][i],
                values[:appendix_a_closed_form][i],
                values[:appendix_a_3d_a7a8][i],
                values[:coulomb_1d][i],
                values[:appendix_a_derivative_g][i],
            ),
        )
    end
end

println("wrote $out")
