#!/usr/bin/env julia
# Recompute residual reports for all `data/reference_spectrum_*.csv` files.

using Dates
using Printf

root = dirname(@__DIR__)
include(joinpath(root, "src", "GIModel", "GIModel.jl"))
using .GIModel

params = load_parameters(joinpath(root, "data", "parameters.provisional.toml"))
data_dir = joinpath(root, "data")
report_dir = joinpath(root, "docs", "residual_reports")
mkpath(report_dir)

const FLAVOR = Dict(
    "reference_spectrum_charmonium.csv" => "c",
    "reference_spectrum_bottomonium.csv" => "b",
    "reference_spectrum_charmed.csv" => "c",
    "reference_spectrum_b_flavored.csv" => "b",
    "reference_spectrum_strange.csv" => "q",
    "reference_spectrum_isovector.csv" => "q",
    "reference_spectrum_isoscalar.csv" => "q",
)

score_rows = NamedTuple[]

for fn in readdir(data_dir)
    startswith(fn, "reference_spectrum_") && endswith(fn, ".csv") || continue
    flavor = get(FLAVOR, fn, "q")
    ref_path = joinpath(data_dir, fn)
    base = fn[(length("reference_spectrum_")+1):(end-length(".csv"))]
    report_path = joinpath(report_dir, string(base, "_residuals.md"))
    title = @sprintf("Residuals: %s (GI-style)", base)
    reference = load_reference_spectrum(ref_path)
    rows = compare_sector(
        params,
        reference,
        flavor;
        kinetic = :relativistic,
        contact_hyperfine = true,
        use_fine_structure = params.fine_structure,
    )
    write_residual_report(
        report_path,
        title,
        rows;
        kinetic = :relativistic,
        contact_hyperfine = true,
        appendix_a_smearing = params.appendix_a_smearing,
        appendix_a_derivative_g = params.appendix_a_derivative_g,
        appendix_a_closed_form = params.appendix_a_closed_form,
        appendix_a_momentum_sandwich = params.appendix_a_momentum_sandwich,
        contact_momentum_sandwich = params.contact_momentum_sandwich,
        fine_structure_momentum_sandwich = params.fine_structure_momentum_sandwich,
        fine_structure_smeared_kernels = params.fine_structure_smeared_kernels,
        coulomb_1d_smear = params.coulomb_1d_smear,
        use_fine_structure = params.fine_structure,
    )
    absres = [abs(r.residual_MeV) for r in rows]
    isempty(absres) && @printf("%s: no rows\n", fn)
    if !isempty(absres)
        mean_abs = sum(absres) / length(absres)
        max_abs = maximum(absres)
        @printf(
            "%s: n=%d mean_abs=%.1f max_abs=%.1f\n",
            fn,
            length(rows),
            mean_abs,
            max_abs
        )
        push!(
            score_rows,
            (
                sector = base,
                n = length(rows),
                mean_abs = mean_abs,
                max_abs = max_abs,
                report = string(base, "_residuals.md"),
            ),
        )
    end
end

open(joinpath(report_dir, "scorecard.md"), "w") do io
    println(io, "# Spectrum Reproduction Scorecard")
    println(io)
    println(io, "Generated by `julia --project=. scripts/run_all_spectrum_checks.jl`.")
    println(
        io,
        "Host generation time: ",
        Dates.format(Dates.now(), dateformat"yyyy-mm-dd\THH:MM"),
    )
    println(io)
    println(io, "| sector | rows | mean abs MeV | max abs MeV | report |")
    println(io, "|---|---:|---:|---:|---|")
    for row in sort(score_rows; by = r -> r.mean_abs)
        println(
            io,
            @sprintf(
                "| `%s` | %d | %.1f | %.1f | [%s](%s) |",
                row.sector,
                row.n,
                row.mean_abs,
                row.max_abs,
                row.report,
                row.report
            )
        )
    end
    println(io)
    println(
        io,
        "Interpretation: heavy-heavy and heavy-light sectors are useful solver diagnostics. Light and isoscalar sectors still require the missing GI mixing/annihilation machinery and should not be treated as complete.",
    )
end
