name: Test

on:
    push:
        branches:
            - main
        tags: ["*"]
    workflow_dispatch:

jobs:
    test:
        uses: ./.github/workflows/ReusableTest.yml
        with:
            project: ${{ matrix.project }}
            os: ${{ matrix.os }}
            version: ${{ matrix.version }}
            allow_failure: ${{ matrix.allow_failure }}
            run_codecov: ${{ matrix.version == '1' && matrix.os == 'ubuntu-24.04' }}
        secrets:
            codecov_token: ${{ secrets.CODECOV_TOKEN }}
        strategy:
            fail-fast: false
            matrix:
                project:
                    - "."
                    - GIPaper
                version:
                    - "1.11"
                    - "1"
                os:
                    - ubuntu-24.04
                    - macOS-latest
                    - windows-latest
                allow_failure: [false]
